### ISSUE TITLE
Please fix this bug

### ISSUE THREAD

**Issue by atefganm** [fairbird/openpli-dreambox-oe-core#1]
`Build Configuration:
BB_VERSION           = "1.51.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "develop"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
BOX_BRAND            = "dreambox"
SOC_FAMILY           = "bcm7435"
KERNELVERSION        = "3.4"
RCNAME               = "dmm2"
DISTRO_FEED_URI      = "https://raw.githubusercontent.com/atefganm/Hains-Raed-OpenPliFeed/develop"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:73d5cd5e8d9d8a922b6a8a9d90adf0470a99314e"
meta                 = "HEAD:a6cc842973f8e3d5a72e6f4012d0430777901408"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-openpli         
meta-dreambox        
meta-kodi            = "develop:9258bbfdf01406d6361543fab01f38963446fbb3"

Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:04
Sstate summary: Wanted 704 Local 661 Network 0 Missed 43 Current 1569 (93% match, 98% complete)
Removing 16 stale sstate objects for arch dm820: 100% |#############################################################################################################################################| Time: 0:00:00
Removing 14 stale sstate objects for arch mips32el: 100% |##########################################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
WARNING: openpli-enigma2-image-1.0-r0 do_rootfs: busybox.postinst returned 1, marking as unpacked only, configuration required on target.
ERROR: openpli-enigma2-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['busybox'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
Details of the failure are in /home/atef/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/temp/log.do_rootfs.
ERROR: Logfile of failure stored in: /home/atef/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/openpli-enigma2-image/1.0-r0/temp/log.do_rootfs.2965820
ERROR: Task (/home/atef/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6878 tasks of which 6619 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb:do_rootfs
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:107: image] Error 1
atef@ganm:~/openpli-dreambox-oe-core$ 

`

**Comment by fairbird** [comment]
Are you sure you are using our meta-dreambox ?!! and our complete core without changing any things ?!!
See in your log what shown ?!
>DISTRO = "openpli"
DISTRO_VERSION = "develop"

should be like this
> DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-11.1"

So, If you using different recipes or complete different meta then you should be to fix it by yourself. Not fix the core files
And I can not change our files and make it compatible with outside extra files.

**Comment by fairbird** [comment]
No problem (every things done without and error)
So As I guess you are using different meta (You need to fix it) .. 

> raed@fairbird:~/build_image/US-Openpli/openpli-dreambox-oe-core$ make image
Building image for 
Loading cache: 100% |                                                                                                                        | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |#######################################################################################################################| Time: 0:03:10
Parsing of 3250 .bb files complete (0 cached, 3250 parsed). 4836 targets, 403 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.51.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-11.1"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
BOX_BRAND            = "dreambox"
SOC_FAMILY           = "bcm7435"
KERNELVERSION        = "3.4"
RCNAME               = "dmm2"
DISTRO_FEED_URI      = "http://fairbird/feeds/openpli-GCC-11.1"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:73d5cd5e8d9d8a922b6a8a9d90adf0470a99314e"
meta                 = "HEAD:a6cc842973f8e3d5a72e6f4012d0430777901408"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-openpli         
meta-dreambox        
meta-kodi            = "develop:3f02922933f4786b545fbea91d47cf64c27a8ceb"

Initialising tasks: 100% |####################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 1795 Local 57 Network 0 Missed 1738 Current 335 (3% match, 18% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 6501 tasks of which 1799 didn't need to be rerun and all succeeded.
raed@fairbird:~/build_image/US-Openpli/openpli-dreambox-oe-core$

Close issue !
