### ISSUE TITLE
python 3.12.7

### ISSUE THREAD

**Issue by satfreak0** [fairbird/openpli-dreambox-oe-core#100]
hallo fairbird,
can you add a githup project with python 3.12.6 ?
my external plugins is not working with version 3.13.0....(:

thanks and regards

**Comment by fairbird** [comment]
Sorry I can not .. I have already upgraded the python version to 3.13. So no way to go back to old version 3.12 !
You need to update your plugins to make it compatible with python 3.13 !

All Opensource team such as openATV .. etc will be move to python 3.13 as soon as possible.
