### ISSUE TITLE
enigma2.bb:do_compile) failed with exit code '1'

### ISSUE THREAD

**Issue by elhawarynas** [fairbird/openpli-dreambox-oe-core#101]
[log.do_compile.278168.zip](https://github.com/user-attachments/files/18194493/log.do_compile.278168.zip)

**Comment by fairbird** [comment]
Solved !
https://github.com/fairbird/enigma2-dreambox/commit/dbaf1518ce91b3d8a9e555d7b53200829dbce9f3
