### ISSUE TITLE
ERROR   enigma2-channelsettings

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#11]
ERROR: ExpansionError during parsing /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-9e-13e-19e-23e-28e.bb
remote https://github.com/haroo/HansSettings.git  failed with exit code 128, output:
fatal: could not read Username for 'https://github.com': No such device or address
look
https://github.com/haroo/HansSettings

**Comment by elhawaryna** [comment]
check internet connection: Online      
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 4257 entries from dependency cache.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-13e-19e-23e-28e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-9e-13e-19e-23e-28e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-30w-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-19e-23e-28e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-9e-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-4.8e-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-16e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-motor.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-42e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-19e-23e-basis.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-4.8e-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-kabelnl.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-16e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-42e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-23.5e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-23.5e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-19e-23e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-9e-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-9e-13e-19e-23e-28e-rotating.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-30w-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-4.8e-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-13e-19.2e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-23.5e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-16e-19.2e-23.5e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
Parsing recipes: 100% |##########################################| Time: 0:00:15
Parsing of 3105 .bb files complete (2832 cached, 273 parsed). 4529 targets, 442 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'bitratecalc' (but /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'bitratecalc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['bitratecalc']
ERROR: Required build target 'openpli-enigma2-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-image', 'bitratecalc']

Summary: There were 30 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:108: image] Error 1
elhawary@elhawary-MS-7848:~/p3/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
I will remove it from source I think the HansSettings deleted ...

**Comment by fairbird** [comment]
Updated Url
https://github.com/fairbird/openpli-dreambox-oe-core/commit/d46b2eeace442c53ca65b6ec847fa8a24e976dd7

**Comment by elhawaryna** [comment]
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-23.5e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-motor.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-16e-19.2e-23.5e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-4.8e-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-19e-23e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-42e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-4.8e-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-9e-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-19e-23e-basis.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-9e-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-23.5e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-42e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-4.8e-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-30w-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-16e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-19.2e-23.5e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-13e-16e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-13e-19e-23e-28e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-kabelnl.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-9e-13e-19e-23e-28e-rotating.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-13e-19.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-19e-23e-28e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-30w-13e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-hans-9e-13e-19e-23e-28e.bb: URL: git://gitlab.openpli.org/openpli/hanssettings.git;protocol=http does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
WARNING: /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-channelsettings/enigma2-plugin-settings-morph883-0.8w-13e-19.2e-28.2e.bb: URL: git://github.com/morpheus883/Enigma2-Settings.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
NOTE: Resolving any missing task queue dependencies

**Comment by fairbird** [comment]
This is just warning any way ...
I have changed it from http to https ..
https://github.com/fairbird/openpli-dreambox-oe-core/commit/cd3f36f009efdf56b1bf5ab51b8af095fb772765
