### ISSUE TITLE
'fix-temperature-url.patch

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#14]
ERROR: enigma2-plugin-extensions-hetweer-2.0+gitAUTOINC+4f9474d82d-r1 do_patch: Applying patch 'fix-temperature-url.patch' on target directory '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-hetweer/2.0+gitAUTOINC+4f9474d82d-r1/git'
CmdError('quilt --quiltrc /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-hetweer/2.0+gitAUTOINC+4f9474d82d-r1/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch fix-temperature-url.patch
patching file plugin/plugin.py
Hunk #1 FAILED at 1048.
1 out of 1 hunk FAILED -- rejects in file plugin/plugin.py
Patch fix-temperature-url.patch can be reverse-applied

stderr: ')
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-hetweer/2.0+gitAUTOINC+4f9474d82d-r1/temp/log.do_patch.1075270
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/e2openplugins/enigma2-plugin-extensions-hetweer.bb:do_patch) failed with exit code '1'

**Comment by fairbird** [comment]
Solved !
https://github.com/fairbird/openpli-dreambox-oe-core/commit/719deb962929a44cdee3014ede23e6f7a6770352
