### ISSUE TITLE
linux-dreambox_3.4.bb:do_compile) failed 

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#15]
Sstate summary: Wanted 2187 Local 10 Mirrors 0 Missed 2177 Current 459 (0% match, 17% complete)
NOTE: Executing Tasks
NOTE: Running setscene task 1348 of 2646 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/base-files/base-files_3.0.14.bb:do_package_write_ipk_setscene)
NOTE: Running setscene task 1424 of 2646 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/glibc/glibc_2.36.bb:do_package_write_ipk_setscene)
NOTE: Running setscene task 1530 of 2646 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/update-rc.d/update-rc.d_0.8.bb:do_package_write_ipk_setscene)
NOTE: Running setscene task 1537 of 2646 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/autoconf-archive/autoconf-archive_2022.02.11.bb:do_package_write_ipk_setscene)
NOTE: recipe base-files-3.0.14-r89: task do_package_write_ipk_setscene: Started
NOTE: recipe autoconf-archive-2022.02.11-r0: task do_package_write_ipk_setscene: Started
NOTE: recipe update-rc.d-0.8-r0: task do_package_write_ipk_setscene: Started
NOTE: recipe glibc-2.36-r0: task do_package_write_ipk_setscene: Started
NOTE: recipe base-files-3.0.14-r89: task do_package_write_ipk_setscene: Succeeded
NOTE: recipe glibc-2.36-r0: task do_package_write_ipk_setscene: Succeeded
NOTE: recipe update-rc.d-0.8-r0: task do_package_write_ipk_setscene: Succeeded
NOTE: recipe autoconf-archive-2022.02.11-r0: task do_package_write_ipk_setscene: Succeeded
NOTE: Running setscene task 2003 of 2646 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-kernel/linux-libc-headers/linux-libc-headers_5.19.bb:do_package_write_ipk_setscene)
NOTE: recipe linux-libc-headers-5.19-r0: task do_package_write_ipk_setscene: Started
NOTE: recipe linux-libc-headers-5.19-r0: task do_package_write_ipk_setscene: Succeeded
NOTE: Setscene tasks completed
NOTE: Running task 552 of 6375 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/gcc/libgcc_12.1.bb:do_install)
NOTE: recipe libgcc-12.1.0-r0: task do_install: Started
NOTE: Running task 996 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/rust/rust-llvm_1.62.1.bb:do_install)
NOTE: Running task 1449 of 6375 (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/linux/linux-dreambox_3.4.bb:do_compile)
NOTE: Running task 1532 of 6375 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-cryptography_37.0.4.bb:do_patch)
NOTE: recipe rust-llvm-native-1.62.1-r0: task do_install: Started
NOTE: recipe python3-cryptography-37.0.4-r0: task do_patch: Started
NOTE: recipe linux-dreambox-3.4-r14: task do_compile: Started
NOTE: recipe python3-cryptography-37.0.4-r0: task do_patch: Succeeded
NOTE: Running task 1533 of 6375 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-cryptography_37.0.4.bb:do_populate_lic)
NOTE: recipe python3-cryptography-37.0.4-r0: task do_populate_lic: Started
NOTE: recipe python3-cryptography-37.0.4-r0: task do_populate_lic: Succeeded
NOTE: Running task 1534 of 6375 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-cryptography_37.0.4.bb:do_rust_gen_targets)
NOTE: recipe python3-cryptography-37.0.4-r0: task do_rust_gen_targets: Started
NOTE: recipe python3-cryptography-37.0.4-r0: task do_rust_gen_targets: Succeeded
NOTE: Running task 1535 of 6375 (/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-cryptography_37.0.4.bb:do_deploy_source_date_epoch)
NOTE: recipe python3-cryptography-37.0.4-r0: task do_deploy_source_date_epoch: Started
NOTE: recipe python3-cryptography-37.0.4-r0: task do_deploy_source_date_epoch: Succeeded
NOTE: Running task 1537 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_prepare_recipe_sysroot)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_prepare_recipe_sysroot: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_prepare_recipe_sysroot: Succeeded
NOTE: Running task 1538 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_unpack)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_unpack: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_unpack: Succeeded
NOTE: Running task 1539 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_patch)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_patch: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_patch: Succeeded
NOTE: Running task 1540 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_populate_lic)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_populate_lic: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_populate_lic: Succeeded
NOTE: Running task 1541 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_deploy_source_date_epoch)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_deploy_source_date_epoch: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_deploy_source_date_epoch: Succeeded
NOTE: Running task 1542 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_configure)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_configure: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_configure: Succeeded
NOTE: Running task 1543 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_compile)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_compile: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_compile: Succeeded
NOTE: Running task 1544 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_install)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_install: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_install: Succeeded
NOTE: Running task 1545 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_populate_sysroot)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_populate_sysroot: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_populate_sysroot: Succeeded
NOTE: Running task 1546 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-setuptools-rust_0.12.1.bb:do_rm_work)
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_rm_work: Started
NOTE: recipe python3-setuptools-rust-native-0.12.1-r0: task do_rm_work: Succeeded
NOTE: Running task 1547 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_fetch)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_fetch: Started
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_fetch: Succeeded
NOTE: Running task 1548 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_prepare_recipe_sysroot)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_prepare_recipe_sysroot: Started
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_prepare_recipe_sysroot: Succeeded
NOTE: Running task 1549 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_unpack)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_unpack: Started
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_unpack: Succeeded
NOTE: Running task 1550 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_patch)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_patch: Started
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_patch: Succeeded
NOTE: Running task 1551 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_populate_lic)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_populate_lic: Started
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_populate_lic: Succeeded
NOTE: Running task 1552 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_deploy_source_date_epoch)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_deploy_source_date_epoch: Started
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_deploy_source_date_epoch: Succeeded
NOTE: Running task 1553 of 6375 (virtual:native:/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-semantic-version_2.8.5.bb:do_configure)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_configure: Started
ERROR: linux-dreambox-3.4-r14 do_compile: oe_runmake failed
ERROR: linux-dreambox-3.4-r14 do_compile: ExecutionError('/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/linux-dreambox/3.4-r14/temp/run.do_compile.917583', 1, None, None)
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/linux-dreambox/3.4-r14/temp/log.do_compile.917583
NOTE: recipe linux-dreambox-3.4-r14: task do_compile: Failed
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/linux/linux-dreambox_3.4.bb:do_compile) failed with exit code '1'
NOTE: Running task 1554 of 6375 (/home/elhawary/openpli-dreambox-oe-core/meta-openembedded/meta-oe/recipes-multimedia/libopus/libopus_1.3.1.bb:do_fetch)
NOTE: recipe python3-semantic-version-native-2.8.5-r0: task do_configure: Succeeded
NOTE: recipe libopus-1.3.1-r0: task do_fetch: Started
NOTE: recipe libopus-1.3.1-r0: task do_fetch: Succeeded
NOTE: recipe rust-llvm-native-1.62.1-r0: task do_install: Succeeded
NOTE: recipe libgcc-12.1.0-r0: task do_install: Succeeded
NOTE: Tasks Summary: Attempted 1554 tasks of which 1529 didn't need to be rerun and 1 failed.

**Comment by elhawaryna** [comment]
ERROR: linux-dreambox-3.2-r14.7 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/elhawary/openpli-dreambox-oe-core/openembedded-core/scripts:/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/recipe-sysroot/usr/bin/crossscripts:/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/recipe-sysroot-native/usr/sbin:/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/recipe-sysroot-native/usr/bin:/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/recipe-sysroot-native/sbin:/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/recipe-sysroot-native/bin:/home/elhawary/openpli-dreambox-oe-core/bitbake/bin:/home/elhawary/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/elhawary"; /usr/bin/env wget -t 2 -T 30 --passive-ftp -O /home/elhawary/openpli-dreambox-oe-core/sources/linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch.bz2.tmp -P /home/elhawary/openpli-dreambox-oe-core/sources 'http://sources.dreamboxupdate.com/download/kernel-patches/linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch.bz2' --progress=dot -v failed with exit code 5, no output
ERROR: linux-dreambox-3.2-r14.7 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://sources.dreamboxupdate.com/download/kernel-patches/linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch.bz2;name=dream-patch')
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm500hd-oe-linux/linux-dreambox/3.2-r14.7/temp/log.do_fetch.1000609
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/linux/linux-dreambox_3.2.bb:do_fetch) failed with exit code '1'

**Comment by fairbird** [comment]
This logo is useless... Send me the file for full construction
Also, you should delete the build folder completely, not just tmp and build the image again...

But I think you have connection issue see the log what says 
> wget -t 2 -T 30 --passive-ftp -O /home/elhawary/openpli-dreambox-oe-core/sources/linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch.bz2.tmp -P /home/elhawary/openpli-dreambox-oe-core/sources 'http://sources.dreamboxupdate.com/download/kernel-patches/linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch.bz2' --progress=dot -v failed with exit code 5, no output
ERROR: linux-dreambox-3.2-r14.7 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://sources.dreamboxupdate.com/download/kernel-patches/linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch.bz2;name=dream-patch')

**_FetchError('Unable to fetch URL from any source.',_**

**Comment by fairbird** [comment]
Please try after this commit and give feedback
https://github.com/fairbird/openpli-dreambox-oe-core/commit/b9b9c75b26326ede300b5d79799bf83f82aa962b

P.s: Do not forget to delete tmp directory ....

**Comment by elhawaryna** [comment]
Everything is fine except for 820
https://www.mediafire.com/file/h1eq2a1bqk29d4z/console-latest.log/file

**Comment by fairbird** [comment]
Solved ... Please try again
