### ISSUE TITLE
/linux-dreambox_3.4.bb:do_compile) failed

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#16]
NOTE: Executing Tasks
NOTE: Running setscene task 4028 of 4851 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-crossepg.bb:do_package_setscene)
NOTE: recipe enigma2-plugin-systemplugins-crossepg-0.9.0+gitrAUTOINC+467b7f986f-r0: task do_package_setscene: Started
NOTE: recipe enigma2-plugin-systemplugins-crossepg-0.9.0+gitrAUTOINC+467b7f986f-r0: task do_package_setscene: Succeeded
NOTE: Setscene tasks completed
NOTE: Running task 1958 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/linux/linux-dreambox_3.4.bb:do_compile)
NOTE: recipe linux-dreambox-3.4-r14: task do_compile: Started
NOTE: Running task 3315 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_fetch)
NOTE: recipe enigma2-3.10+gitAUTOINC+13e689c523-r0: task do_fetch: Started
NOTE: Running task 4164 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugin-multibox-dvbmediasink.bb:do_packagedata)
NOTE: Running task 4405 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_fetch)
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_packagedata: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_fetch: Started
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_packagedata: Succeeded
NOTE: Running task 4406 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugin-multibox-dvbmediasink.bb:do_package_qa)
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_package_qa: Started
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_package_qa: Succeeded
NOTE: Running task 4407 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugin-multibox-dvbmediasink.bb:do_package_write_ipk)
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_package_write_ipk: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_fetch: Succeeded
NOTE: Running task 4408 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_prepare_recipe_sysroot)
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_package_write_ipk: Succeeded
NOTE: Running task 4409 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugin-multibox-dvbmediasink.bb:do_rm_work)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_prepare_recipe_sysroot: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_prepare_recipe_sysroot: Succeeded
NOTE: Running task 4410 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_unpack)
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_rm_work: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_unpack: Started
NOTE: recipe enigma2-3.10+gitAUTOINC+13e689c523-r0: task do_fetch: Succeeded
NOTE: Running task 4411 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_prepare_recipe_sysroot)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_unpack: Succeeded
NOTE: Running task 4412 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_patch)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_patch: Started
NOTE: recipe enigma2-3.10+gitAUTOINC+13e689c523-r0: task do_prepare_recipe_sysroot: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_patch: Succeeded
NOTE: Running task 4413 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_populate_lic)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_populate_lic: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_populate_lic: Succeeded
NOTE: Running task 4414 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_deploy_source_date_epoch)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_deploy_source_date_epoch: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_deploy_source_date_epoch: Succeeded
NOTE: Running task 4415 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_configure)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_configure: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_configure: Succeeded
NOTE: Running task 4416 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_compile)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_compile: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_compile: Succeeded
NOTE: Running task 4417 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_install)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_install: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_install: Succeeded
NOTE: Running task 4418 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_package)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_package: Started
ERROR: linux-dreambox-3.4-r14 do_compile: oe_runmake failed
ERROR: linux-dreambox-3.4-r14 do_compile: ExecutionError('/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/linux-dreambox/3.4-r14/temp/run.do_compile.1828386', 1, None, None)
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/linux-dreambox/3.4-r14/temp/log.do_compile.1828386
NOTE: recipe linux-dreambox-3.4-r14: task do_compile: Failed
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/linux/linux-dreambox_3.4.bb:do_compile) failed with exit code '1'
NOTE: Running task 4419 of 11164 (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pli-hd.bb:do_populate_sysroot)
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_populate_sysroot: Started
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_populate_sysroot: Succeeded
NOTE: recipe gstreamer1.0-plugin-multibox-dvbmediasink-1.0+gitAUTOINC+02dc987068-r0: task do_rm_work: Succeeded
NOTE: recipe enigma2-3.10+gitAUTOINC+13e689c523-r0: task do_prepare_recipe_sysroot: Succeeded
NOTE: recipe enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+5ecb383322-r0: task do_package: Succeeded
NOTE: Tasks Summary: Attempted 4419 tasks of which 4401 didn't need to be rerun and 1 failed.

**Comment by fairbird** [comment]
meta-dream Still need update (Wait) ...
But you need also to delete tmp folder then start to compile image again ...

**Comment by fairbird** [comment]
Update done !!
Please try again !!
