### ISSUE TITLE
ERROR: Nothing PROVIDES 'firmware

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#19]
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'firmware-dvb-fe-cx24117' (but /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb DEPENDS on or otherwise requires it). Close matches:
  firmware-dvb-fe-drxk
  firmware-dvb-fe-si2168
  firmware-dvb-fe-xc5000-1.1
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'firmware-dvb-fe-cx24117']

**Comment by elhawaryna** [comment]
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'firmware-mt7650' (but /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb DEPENDS on or otherwise requires it). Close matches:
  firmware-mt7601u
  firmware-rt2870
  firmware-rt73
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'firmware-mt7650']

**Comment by fairbird** [comment]
1-What boxes ?!!
2-I have update core so you need to delete tmp folder ..
https://github.com/fairbird/openpli-dreambox-oe-core/commit/5b5ce42e4a3783377304f021f6703612387631e3

I have built feed to DM520, 7080 and 920 without any error ...

**Comment by elhawaryna** [comment]
820

**Comment by elhawaryna** [comment]
820
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'firmware-dvb-demod-si2168-d60' (but /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb DEPENDS on or otherwise requires it). Close matches:
  firmware-dvb-demod-si2168-a20
  firmware-dvb-demod-si2168-a30
  firmware-dvb-demod-si2168-b40
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'firmware-dvb-demod-si2168-d60']

**Comment by fairbird** [comment]
Ok.. I will check DM820 as soon as possible.

**Comment by fairbird** [comment]
Please try again after this commit ...
https://github.com/fairbird/openpli-dreambox-oe-core/commit/1f13895ab63234506399dbb23437c3a6edf7b20b
