### ISSUE TITLE
streamlink

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#26]
ERROR: streamlink-gitAUTOINC+e2c8e46018_9d95a0244a-r0 do_populate_lic: QA Issue: streamlink: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=381ff91bf309000e0ec58dafe27a97b0
streamlink: The new md5 checksum is b026f0197dc4ce773b97e3dc1f55f55c
streamlink: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Copyright (c) 2011-2016, Christopher Rosell
Copyright (c) 2016-2023, Streamlink Team
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
...
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
streamlink: Check if the license information has changed in /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/streamlink/gitAUTOINC+e2c8e46018_9d95a0244a-r0/git/LICENSE to verify that the LICENSE value "BSD-2-Clause" remains valid [license-checksum]
ERROR: streamlink-gitAUTOINC+e2c8e46018_9d95a0244a-r0 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/streamlink/gitAUTOINC+e2c8e46018_9d95a0244a-r0/temp/log.do_populate_lic.2876444
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/streamlink_git.bb:do_populate_lic) failed with exit code '1'
///////////////////////////////////
dm520
ERROR: streamlink-gitAUTOINC+e2c8e46018_9d95a0244a-r0 do_populate_lic: QA Issue: streamlink: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=381ff91bf309000e0ec58dafe27a97b0
streamlink: The new md5 checksum is b026f0197dc4ce773b97e3dc1f55f55c
streamlink: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Copyright (c) 2011-2016, Christopher Rosell
Copyright (c) 2016-2023, Streamlink Team
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
...
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
streamlink: Check if the license information has changed in /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/streamlink/gitAUTOINC+e2c8e46018_9d95a0244a-r0/git/LICENSE to verify that the LICENSE value "BSD-2-Clause" remains valid [license-checksum]
ERROR: streamlink-gitAUTOINC+e2c8e46018_9d95a0244a-r0 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/streamlink/gitAUTOINC+e2c8e46018_9d95a0244a-r0/temp/log.do_populate_lic.2147169
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/streamlink_git.bb:do_populate_lic) failed with exit code '1'
*********************************
dm7080
ERROR: streamlink-gitAUTOINC+e2c8e46018_9d95a0244a-r0 do_populate_lic: QA Issue: streamlink: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=381ff91bf309000e0ec58dafe27a97b0
streamlink: The new md5 checksum is b026f0197dc4ce773b97e3dc1f55f55c
streamlink: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Copyright (c) 2011-2016, Christopher Rosell
Copyright (c) 2016-2023, Streamlink Team
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
...
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
streamlink: Check if the license information has changed in /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/streamlink/gitAUTOINC+e2c8e46018_9d95a0244a-r0/git/LICENSE to verify that the LICENSE value "BSD-2-Clause" remains valid [license-checksum]
ERROR: streamlink-gitAUTOINC+e2c8e46018_9d95a0244a-r0 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/streamlink/gitAUTOINC+e2c8e46018_9d95a0244a-r0/temp/log.do_populate_lic.2189907
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/streamlink_git.bb:do_populate_lic) failed with exit code '1'

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/d82a76a7e4846f9b431d0cd203810302dc8cd321
