### ISSUE TITLE
backupflash

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#28]
ERROR: enigma2-plugin-extensions-backupflash-1.1+gitAUTOINC+d8e053c28e-r0 do_install: ExecutionError('/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/temp/run.do_install.208413', 1, None, None)
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/temp/log.do_install.208413
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/glibc/glibc_2.36.bb:do_populate_sysroot', '/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_12.2.bb:do_populate_sysroot', '/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_12.2.bb:do_populate_sysroot', '/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3_3.11.1.bb:do_populate_sysroot', '/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-installer_0.6.0.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-picobuild_0.2.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-setuptools_65.5.1.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-wheel_0.38.4.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3_3.11.1.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['glibc', 'gcc-cross-mipsel', 'gcc-runtime', 'python3', 'quilt-native', 'patch-native', 'pseudo-native', 'python3-installer-native', 'python3-picobuild-native', 'python3-setuptools-native', 'python3-wheel-native', 'python3-native', 'python3-flit-core-native', 'libtool-native', 'attr-native', 'linux-libc-headers', 'libgcc', 'xz-native', 'readline-native', 'libffi-native', 'libnsl2-native', 'ncurses-native', 'gdbm-native', 'openssl-native', 'libtirpc-native', 'zlib-native', 'sqlite3-native', 'util-linux-libuuid-native', 'bzip2-native', 'openssl', 'sqlite3', 'gdbm', 'libnsl2', 'opkg-utils', 'util-linux-libuuid', 'xz', 'libtirpc', 'libffi', 'zlib', 'ncurses', 'libxcrypt', 'readline', 'bzip2', 'libmpc-native', 'flex-native', 'gnu-config-native', 'zstd-native', 'binutils-cross-mipsel', 'texinfo-dummy-native', 'mpfr-native', 'gmp-native', 'unzip-native', 'gettext-minimal-native', 'perl-native', 'm4-native', 'make-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/plugin.py:63: SyntaxWarning: "is not" with a literal. Did you mean "!="?
|   if cmd.find("root=/dev/sda1") is not -1:
| /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/plugin.py:150: SyntaxWarning: "is" with a literal. Did you mean "=="?
|   if (os.path.exists("/.bainfo") or os.path.exists("/.lfinfo") or cmd.find(rootfs) is -1):
| /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/plugin.py:166: SyntaxWarning: "is" with a literal. Did you mean "=="?
|   if not config.backupflashe.flashAllow.value and (os.path.exists("/.bainfo") or os.path.exists("/.lfinfo") or cmd.find(rootfs) is -1):
| /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/flashonline.py:707: SyntaxWarning: "is not" with a literal. Did you mean "!="?
|   if cmd.find("root=/dev/sda1") is not -1:
| /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/flashonline.py:713: SyntaxWarning: "is" with a literal. Did you mean "=="?
|   if not config.backupflashe.flashAllow.value and (os.path.exists("/.bainfo") or os.path.exists("/.lfinfo") or cmd.find(rootfs) is -1):
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/__init__.py'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/arm64'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/armhf'...
 Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/__init__.py'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/arm64'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/armhf'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/buttons'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/mipsel'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/plugin.py'...
| Listing '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/Console.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/__init__.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/backup.py'...
| *** Sorry: TabError: inconsistent use of tabs and spaces in indentation (backup.py, line 151)
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/bftools.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/compat.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/download.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/flash.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/flashonline.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/progress.py'...
| Compiling '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/backupflashe/tools/skin.py'...
| WARNING: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/temp/run.do_install.208413:158 exit 1 from 'python3 -m compileall -o2 -b /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/image/usr'
| WARNING: Backtrace (BB generated script):
| 	#1: do_install, /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/temp/run.do_install.208413, line 158
| 	#2: main, /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupflash/1.1+gitAUTOINC+d8e053c28e-r0/temp/run.do_install.208413, line 170
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupflash.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9811 tasks of which 9360 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupflash.bb:do_install
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by fairbird** [comment]
It was just white space in some file in backupflash plugin .. Solved !!
https://github.com/fairbird/BackUpFlash/commit/6fb04201b88201e9e3c0576ad04bffe4f3235bfb
