### ISSUE TITLE
ERROR: linux-dreambox-3.4-.14 do_patch

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#35]
dm820

ERROR: linux-dreambox-3.4-.14 do_patch: QA Issue: Fuzz detected:

Applying patch build-with-gcc12-fixes.patch
patching file arch/mips/kernel/module.c
Hunk #2 succeeded at 375 (offset 118 lines).
patching file arch/mips/kernel/traps.c
Hunk #1 succeeded at 16 (offset -2 lines).
Hunk #2 succeeded at 426 (offset 4 lines).
patching file include/linux/extable.h
patching file include/linux/mmzone.h
Hunk #1 succeeded at 1038 (offset -95 lines).
patching file include/linux/module.h
Hunk #1 succeeded at 70 (offset -4 lines).
Hunk #2 succeeded at 78 (offset -4 lines).
patching file init/main.c
Hunk #1 succeeded at 10 with fuzz 1 (offset -2 lines).
patching file kernel/extable.c
patching file kernel/module.c
Hunk #2 succeeded at 3456 (offset -250 lines).

The context lines in the patches can be updated with devtool:

    devtool modify linux-dreambox
    devtool finish --force-patch-refresh linux-dreambox <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]
ERROR: linux-dreambox-3.4-.14 do_patch: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/linux-dreambox/3.4-.14/temp/log.do_patch.3442470
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-linux/linux-dreambox_3.4.bb:do_patch) failed with exit code '1'

**Comment by fairbird** [comment]
That is just warring message not error ...
You need to remove /tmp directory

**Comment by elhawaryna** [comment]
NOTE: Executing Tasks
ERROR: linux-dreambox-3.4-.14 do_patch: QA Issue: Fuzz detected:

Applying patch build-with-gcc12-fixes.patch
patching file arch/mips/kernel/module.c
Hunk #2 succeeded at 375 (offset 118 lines).
patching file arch/mips/kernel/traps.c
Hunk #1 succeeded at 16 (offset -2 lines).
Hunk #2 succeeded at 426 (offset 4 lines).
patching file include/linux/extable.h
patching file include/linux/mmzone.h
Hunk #1 succeeded at 1038 (offset -95 lines).
patching file include/linux/module.h
Hunk #1 succeeded at 70 (offset -4 lines).
Hunk #2 succeeded at 78 (offset -4 lines).
patching file init/main.c
Hunk #1 succeeded at 10 with fuzz 1 (offset -2 lines).
patching file kernel/extable.c
patching file kernel/module.c
Hunk #2 succeeded at 3456 (offset -250 lines).


The context lines in the patches can be updated with devtool:

    devtool modify linux-dreambox
    devtool finish --force-patch-refresh linux-dreambox <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]
ERROR: linux-dreambox-3.4-.14 do_patch: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/linux-dreambox/3.4-.14/temp/log.do_patch.71376
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-linux/linux-dreambox_3.4.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1346 tasks of which 1046 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-linux/linux-dreambox_3.4.bb:do_patch
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$

**Comment by elhawaryna** [comment]
https://www.mediafire.com/file/holvsfclsnp036p/console-latest.zip/file

**Comment by fairbird** [comment]
Log you attach won't to open error (empty)
And Also as I wrote in my previous replay no error shown in you replay ... Just  warring message ..
Remove complete (build) folder and start again ... I will check from my said also to build image later.

**Comment by fairbird** [comment]
Please try again after this  commit ..
https://github.com/fairbird/openpli-dreambox-oe-core/commit/29be83e725b4a1390e411b9a34f366aee5e5927e

**Comment by fairbird** [comment]
Please have a try again after this commit
https://github.com/fairbird/openpli-dreambox-oe-core/commit/472b0528882560e68bd6bf5d5918218efa34d396

**Comment by elhawaryna** [comment]
ERROR: enigma2-plugins-alliance-gitrAUTOINC+ce5b83fa3d-r1 do_patch: QA Issue: Fuzz detected:

Applying patch remove-duplicate-plugins-with-pli-plugins.patch
patching file Makefile.am
Hunk #2 succeeded at 48 (offset -3 lines).
patching file configure.ac
Hunk #2 succeeded at 184 (offset -4 lines).
Hunk #3 succeeded at 192 (offset -4 lines).
Hunk #4 succeeded at 211 (offset -4 lines).
Hunk #5 succeeded at 233 (offset -4 lines).
Hunk #6 succeeded at 246 (offset -5 lines).
Hunk #7 succeeded at 269 (offset -5 lines).
Hunk #8 succeeded at 294 (offset -5 lines).
Hunk #9 succeeded at 308 (offset -5 lines).
Hunk #10 succeeded at 341 (offset -5 lines).
Hunk #11 succeeded at 371 (offset -5 lines).
Hunk #12 succeeded at 384 (offset -5 lines).
Hunk #13 succeeded at 393 (offset -5 lines).
Hunk #14 succeeded at 429 (offset -5 lines).
Hunk #15 succeeded at 459 (offset -5 lines).
Hunk #16 succeeded at 474 with fuzz 1 (offset -5 lines).


The context lines in the patches can be updated with devtool:

    devtool modify enigma2-plugins-alliance
    devtool finish --force-patch-refresh enigma2-plugins-alliance <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]
ERROR: enigma2-plugins-alliance-gitrAUTOINC+ce5b83fa3d-r1 do_patch: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugins-alliance/gitrAUTOINC+ce5b83fa3d-r1/temp/log.do_patch.232987
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9805 tasks of which 1708 didn't need to be rerun and 1 failed.

Summary: 1 task failed:

  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb:do_patch
Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
https://www.mediafire.com/file/pixy8eiaipl66on/20230127032037.tar.xz/file

**Comment by fairbird** [comment]
That is another patch for plugins-alliance
Update it also ...
https://github.com/fairbird/openpli-dreambox-oe-core/commit/d13d59d685ca7969ac364cdb7e52a02a576f45ef

**Comment by elhawaryna** [comment]
Building feed for dm820
check internet connection: Online      
Loading cache: 100% |############################################| Time: 0:00:22
Loaded 4663 entries from dependency cache.
ERROR: ExpansionError during parsing /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/dima-plugins/enigma2-plugin-extensions-tmbd.bb
Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1685, in Fetch.__init__(urls=['git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3', 'file://use-setuptools-instead-of-distutils.patch'], d=<bb.data_smart.DataSmart object at 0x7fb803e7a650>, cache=True, localonly=False, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                     except NonLocalMethod:
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1322, in FetchData.__init__(url='git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3', d=<bb.data_smart.DataSmart object at 0x7fb803e7a650>, localonly=False):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)
     
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 253, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7fb803f00790>, d=<bb.data_smart.DataSmart object at 0x7fb803e7a650>):
     
    >        ud.setup_revisions(d)
     
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1352, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7fb803e7a650>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)
     
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1217, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fb803f00790>, d=<bb.data_smart.DataSmart object at 0x7fb803e7a650>, name='default'):
         if srcrev == "INVALID" or not srcrev:
    >        raise FetchError("Please set a valid SRCREV for url %s (possible key names are %s, or use a ;rev=X URL parameter)" % (str(attempts), ud.url), ud.url)
         if srcrev == "AUTOINC":
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3'. Please set a valid SRCREV for url ['SRCREV_default:pn-enigma2-plugin-extensions-tmbd', 'SRCREV_default', 'SRCREV:pn-enigma2-plugin-extensions-tmbd', 'SRCREV'] (possible key names are git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3, or use a ;rev=X URL parameter)
The variable dependency chain for the failure is: SRCPV -> PV -> BP -> FILESPATH

ERROR: Parsing halted due to errors, see error messages above

Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$

**Comment by elhawaryna** [comment]
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$ MACHINE=dm820 make image
Building image for dm820
check internet connection: Online      
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 4665 entries from dependency cache.
ERROR: ExpansionError during parsing /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/dima-plugins/enigma2-plugin-extensions-tmbd (1).bb
Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1685, in Fetch.__init__(urls=['git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3', 'file://use-setuptools-instead-of-distutils.patch', 'file://port-to-treq.patch'], d=<bb.data_smart.DataSmart object at 0x7f5802b69ed0>, cache=True, localonly=False, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                     except NonLocalMethod:
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1322, in FetchData.__init__(url='git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3', d=<bb.data_smart.DataSmart object at 0x7f5802b69ed0>, localonly=False):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)
     
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 253, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f5802bd1660>, d=<bb.data_smart.DataSmart object at 0x7f5802b69ed0>):
     
    >        ud.setup_revisions(d)
     
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1352, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7f5802b69ed0>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)
     
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1217, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f5802bd1660>, d=<bb.data_smart.DataSmart object at 0x7f5802b69ed0>, name='default'):
         if srcrev == "INVALID" or not srcrev:
    >        raise FetchError("Please set a valid SRCREV for url %s (possible key names are %s, or use a ;rev=X URL parameter)" % (str(attempts), ud.url), ud.url)
         if srcrev == "AUTOINC":
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3'. Please set a valid SRCREV for url ['SRCREV_default:pn-enigma2-plugin-extensions-tmbd (1)', 'SRCREV_default', 'SRCREV:pn-enigma2-plugin-extensions-tmbd (1)', 'SRCREV'] (possible key names are git://github.com/Dima73/enigma2-plugin-extensions-tmbd.git;protocol=https;branch=python3, or use a ;rev=X URL parameter)
The variable dependency chain for the failure is: SRCPV -> PV -> BP -> FILESPATH

ERROR: Parsing halted due to errors, see error messages above

Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Error 1
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
That issue not from source .. It is from internet can not reach to github.com/Dima73 ...
With me no problem yesterday I have compile complete image without any error ...

> Initialising tasks: 100% |###########################################################################################################| Time: 0:00:10
Sstate summary: Wanted 888 Local 864 Mirrors 0 Missed 24 Current 2112 (97% match, 99% complete)
Removing 8 stale sstate objects for arch dreamtwo: 100% |############################################################################| Time: 0:00:00
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 7168 tasks of which 7101 didn't need to be rerun and all succeeded.
raed@fairbird:~/build_image/My-OpenPli/openpli-dreambox-oe-core$ 

P.s: Do no compile and publish image right now ... E2 source not ready (A lot of updates need to testing from my side)

**Comment by fairbird** [comment]
It is ready now to compile image ....

**Comment by elhawaryna** [comment]
I am now rebuilding after installing a new system, and I encountered this problem
//////////////////////////////////////////
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openembedded/meta-networking/recipes-connectivity/samba/samba_4.17.4.bb:do_install) failed with exit code '1'

**Comment by fairbird** [comment]
make sure your are install all depends packages ... Also Please send full log not just one or two lines ..  I cannot understand any things with that line only .. Because I have not got that error before .. and no change in samba recipe.

Two images I'm just now finished from compelled for dm920 and Dreamone (No error)

**Comment by elhawaryna** [comment]
https://www.mediafire.com/file/epjbty8v1p3103z/console-latest.zip/file

**Comment by fairbird** [comment]
100% You are forget some thing after install new distribution. Because from long time I did not update samba recipe .. and no error I have got it before to compile samba.

I will try to build complete image + feed with new clone and I will see If I get any error !!

**Comment by fairbird** [comment]
Still feed running build .. but no error with Samba (Every things good here)
.
![Selection_001](https://user-images.githubusercontent.com/1761779/215291825-ff68861c-957c-45a4-afc5-e8dc8752a435.png)

**Comment by fairbird** [comment]
Feed finished built without any problems or error ..
.
![Selection_001](https://user-images.githubusercontent.com/1761779/215294762-f40d8e50-c475-4672-954f-b16cd5b4965e.png)

**Comment by elhawaryna** [comment]
The problem is building the feed, not building the image
-++++++++++++++++++++++++++++++++++++++++++
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$ MACHINE=dm820 make feed
Building feed for dm820
check internet connection: Online      
Loading cache: 100% |############################################| Time: 0:00:01
Loaded 4663 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:00:27
Parsing of 3401 .bb files complete (3102 cached, 299 parsed). 4962 targets, 492 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync

Build Configuration:
BB_VERSION           = "2.2.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-22.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-12.2"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
SOC_FAMILY           = "bcm7435"
RCTYPE               = "0"
RCNAME               = "dmm2"
RCIDNUM              = "2"
DEVELOPER_NAME       = "openpli"
DISTRO_FEED_URI      = "http://www.openpli.net/pli/plip3/820"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:ceceffcb1e3ef4f9ba7708f77c27e30a7aea61e5"
meta                 = "HEAD:76a685bfcf927593eac67157762a53259089ea8a"
meta-openpli         
meta-dreambox        = "develop:c6f19b96f9f24b0a000fedf0f81da9e1e8fa4185"
meta-qt6             = "HEAD:47416406c4017a059d544625a5584765611c2b7a"

Initialising tasks: 100% |#######################################| Time: 0:00:13
Sstate summary: Wanted 1785 Local 1434 Mirrors 0 Missed 351 Current 3628 (80% match, 93% complete)
Removing 11 stale sstate objects for arch dm820: 100% |##########| Time: 0:00:00
NOTE: Executing Tasks
ERROR: enigma2-plugins-alliance-gitrAUTOINC+ce5b83fa3d-r1 do_package: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:populate_packages(d)
     0003:
File: '/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/classes-global/package.bbclass', lineno: 403, function: populate_packages
     0399:SHLIBSWORKDIR = "${PKGDESTWORK}/${MLPREFIX}shlibs2"
     0400:
     0401:python package_do_shlibs() {
     0402:    oe.package.process_shlibs(pkgfiles, d)
 *** 0403:}
     0404:
     0405:python package_do_pkgconfig () {
     0406:    oe.package.process_pkgconfig(pkgfiles, d)
     0407:}
File: '/home/elhawary/openpli-dreambox-oe-core/openembedded-core/meta/classes-global/package.bbclass', lineno: 368, function: getControlLines
     0364:
     0365:python package_package_name_hook() {
     0366:    """
     0367:    A package_name_hook function can be used to rewrite the package names by
 *** 0368:    changing PKG.  For an example, see debian.bbclass.
     0369:    """
     0370:    pass
     0371:}
     0372:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugins-alliance/gitrAUTOINC+ce5b83fa3d-r1/image/../git/po/CONTROL/control'

ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugins-alliance/gitrAUTOINC+ce5b83fa3d-r1/temp/log.do_package.3980738
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb:do_package) failed with exit code '1'
NOTE: Tasks Summary: Attempted 11145 tasks of which 11072 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb:do_package
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$ 
https://www.mediafire.com/file/ftg345n1y5phi8q/20230129052631.zip/file

**Comment by elhawaryna** [comment]
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$ MACHINE=dm820 make image
Building image for dm820
check internet connection: Online      
Loading cache: 100% |##############################################| Time: 0:00:01
Loaded 4663 entries from dependency cache.
Parsing recipes: 100% |############################################| Time: 0:00:30
Parsing of 3401 .bb files complete (3101 cached, 300 parsed). 4962 targets, 492 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync

Build Configuration:
BB_VERSION           = "2.2.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-22.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-12.2"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
SOC_FAMILY           = "bcm7435"
RCTYPE               = "0"
RCNAME               = "dmm2"
RCIDNUM              = "2"
DEVELOPER_NAME       = "openpli"
DISTRO_FEED_URI      = "http://www.openpli.net/pli/plip3/820"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:ceceffcb1e3ef4f9ba7708f77c27e30a7aea61e5"
meta                 = "HEAD:76a685bfcf927593eac67157762a53259089ea8a"
meta-openpli         
meta-dreambox        = "develop:c6f19b96f9f24b0a000fedf0f81da9e1e8fa4185"
meta-qt6             = "HEAD:47416406c4017a059d544625a5584765611c2b7a"

Initialising tasks: 100% |#########################################| Time: 0:00:07
Sstate summary: Wanted 921 Local 880 Mirrors 0 Missed 41 Current 2134 (95% match, 98% complete)
Removing 11 stale sstate objects for arch dm820: 100% |############| Time: 0:00:00
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 7284 tasks of which 7188 didn't need to be rerun and all succeeded.
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
So .. Did you compiled and built complete image finally ?!!
No issues ?!!

**Comment by elhawaryna** [comment]
There is no problem building the image, but the problem is when building the feed
https://www.mediafire.com/file/ftg345n1y5phi8q/20230129052631.zip/file

**Comment by fairbird** [comment]
Already I have asked other friend if he got any problem with build feed and he said never ... early morning he has sent the feedback (no problem)... You also before installed new distribution every things without you fine to build feed ... Just after your installed new distribution. So the problem is from your side not from core ..

**Comment by elhawaryna** [comment]
When this line is deleted
enigma2-plugins-alliance \
No. 184
https://github.com/fairbird/openpli-dreambox-oe-core/blob/c5b2e88b2728f08a4a7add8b88be1b14e11675f0/meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb#L184
The feed is being built
Notice the sugar that follows it with the same meaning, you just changed the place of the words, so is this deletion correct?
Note that there are no files associated with it

**Comment by fairbird** [comment]
enigma2-plugins-alliance and enigma2-alliance-plugins not the same ...
each one have different plugins ... 

enigma2-plugins-alliance
https://github.com/fairbird/openpli-dreambox-oe-core/blob/develop/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb
https://github.com/oe-alliance/oe-alliance-plugins

enigma2-alliance-plugins
https://github.com/fairbird/openpli-dreambox-oe-core/blob/develop/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-alliance-plugins.bb
https://github.com/oe-alliance/enigma2-plugins

**Comment by fairbird** [comment]
I have clean all state of both (enigma2-alliance-plugins) and (enigma2-plugins-alliance) from build directory
> Currently  2 running tasks (3 of 6)  33% |############################################                                                                                        |
0: enigma2-alliance-plugins-gitAUTOINC+3eac376f97-r0 do_cleansstate - 4m4s (pid 88196)
1: enigma2-plugins-alliance-gitrAUTOINC+ce5b83fa3d-r1 do_cleansstate - 3m40s (pid 88205)

And then I have built new feed ... I did not got any issue.
> Currently 10 running tasks (12013 of 12356)  97% |###############    |
0: enigma2-alliance-plugins-gitAUTOINC+3eac376f97-r0 do_fetch - 6m24s (pid 151654)  63% |##          | 121.00 KiB/s
1: enigma2-plugins-alliance-gitrAUTOINC+ce5b83fa3d-r1 do_fetch - 6m20s (pid 152155)  34% |##         | 64.00 KiB/s
2: wvstreams-4.6.1-r0 do_compile - 5m40s (pid 162867)
3: mpd-0.23.9-r0 do_compile - 5m28s (pid 168717)  43% |###                            |
4: samba-4.17.4-r3 do_package_write_ipk - 5m23s (pid 170603)
5: enigma2-plugin-systemplugins-serviceapp-gitAUTOINC+947f62ed5c-r0 do_compile - 2m44s (pid 195917)
6: enigma2-3.11+gitAUTOINC+d0962dd3aa-r0 do_package_write_ipk - 2m0s (pid 200437)
7: rt8723bs-4.4.1-r3 do_compile - 1m29s (pid 206930)
8: rt8814au-4.3.21-r0 do_compile - 1m10s (pid 208661)

**Comment by elhawaryna** [comment]
After today's updates it's all ok
-+++++++++++++++++++++++
Updating Git repositories...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (6/6), 745 bytes | 12.00 KiB/s, done.
From https://github.com/fairbird/openpli-dreambox-oe-core
   c5b2e88b..886413fc  develop    -> origin/develop
Updating c5b2e88b..886413fc
Fast-forward
 .../recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb  | 9 ++++++++-
 1 file changed, 8 insertions(+), 1 deletion(-)
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-qt6'
Synchronizing submodule url for 'openembedded-core'
The openpli OE is now up-to-date.
