### ISSUE TITLE
ERROR: openpli-enigma2-image-1.0-r0 do_rootfs

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#37]
ERROR: openpli-enigma2-image-1.0-r0 do_rootfs: Unable to install packages. Command '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm520-oe-linux/openpli-enigma2-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm520-oe-linux/openpli-enigma2-image/1.0-r0/opkg.conf -t /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm520-oe-linux/openpli-enigma2-image/1.0-r0/temp/ipktemp/ -o /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm520-oe-linux/openpli-enigma2-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install aio-grab alsa-plugins avahi-daemon ca-certificates cdtextinfo cifs-utils cronie dhrystone distro-feed-configs dropbear e2fsprogs-e2fsck e2fsprogs-mke2fs e2fsprogs-tune2fs enigma2 enigma2-plugin-extensions-arabicsavior enigma2-plugin-extensions-audiosync enigma2-plugin-extensions-autobackup enigma2-plugin-extensions-backupflash enigma2-plugin-extensions-bitrate enigma2-plugin-extensions-cdinfo enigma2-plugin-extensions-cutlisteditor enigma2-plugin-extensions-dvdplayer enigma2-plugin-extensions-epgimport enigma2-plugin-extensions-filecommander enigma2-plugin-extensions-graphmultiepg enigma2-plugin-extensions-internetspeedtest enigma2-plugin-extensions-keyadder enigma2-plugin-extensions-mediaplayer enigma2-plugin-extensions-mediascanner enigma2-plugin-extensions-moviecut enigma2-plugin-extensions-netcaster enigma2-plugin-extensions-openwebif enigma2-plugin-extensions-pictureplayer enigma2-plugin-extensions-subssupport enigma2-plugin-extensions-systemtools enigma2-plugin-extensions-tmbd enigma2-plugin-extensions-xtraevent enigma2-plugin-extensions-youtube enigma2-plugin-softcams-ncam enigma2-plugin-softcams-oscam enigma2-plugin-systemplugins-cablescan enigma2-plugin-systemplugins-commoninterfaceassignment enigma2-plugin-systemplugins-fastscan enigma2-plugin-systemplugins-hdmicec enigma2-plugin-systemplugins-hotplug enigma2-plugin-systemplugins-networkbrowser enigma2-plugin-systemplugins-osd3dsetup enigma2-plugin-systemplugins-osdpositionsetup enigma2-plugin-systemplugins-positionersetup enigma2-plugin-systemplugins-satfinder enigma2-plugin-systemplugins-serviceapp enigma2-plugin-systemplugins-softwaremanager enigma2-plugin-systemplugins-videoenhancement enigma2-plugin-systemplugins-videomode enigma2-plugin-systemplugins-videotune enigma2-plugin-systemplugins-wirelesslan exteplayer3 ffmpeg fuse-exfat glibc-binary-localedata-en-gb gstreamer1.0-plugins-base-volume gstreamer1.0-plugins-good-equalizer gstreamer1.0-plugins-good-mpg123 gstreamer1.0-plugins-good-ossaudio hdparm kernel-params libavahi-client modutils-loadscript mtd-utils mtd-utils-ubifs network-usb-drivers-meta nfs-utils nfs-utils-client openpli-bootlogo openssh-sftp-server opkg packagegroup-base packagegroup-core-boot parted pigz python3-compat2 python3-ipaddress python3-netifaces python3-pycurl python3-pysmb python3-requests run-postinsts samba sdparm settings-autorestore stb-hwclock tuxbox-common tzdata util-linux-ionice util-linux-mount volatile-media vsftpd wget xz' returned 255:
 * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'enigma2-plugin-extensions-cutlisteditor'.

ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm520-oe-linux/openpli-enigma2-image/1.0-r0/temp/log.do_rootfs.3781185
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 12269 tasks of which 11313 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb:do_rootfs
Summary: There was 1 ERROR message, returning a non-zero exit code.

https://www.mediafire.com/file/oi2nu260fm5drs6/20230219122557.zip/file

**Comment by fairbird** [comment]
> * Couldn't find anything to satisfy

That is mean (Some sstchache missing) in your environment builder
 Problem not from the core ...
So remove /tmp directory then build image again ... 
Because CutListEditor plugin it is part of enigma2 and should be built it with image direct without any problem ...
https://github.com/fairbird/enigma2-dreambox/tree/develop/lib/python/Plugins/Extensions/CutListEditor
https://github.com/fairbird/openpli-dreambox-oe-core/blob/develop/meta-openpli/recipes-openpli/enigma2/enigma2.bb#L149-L150

With me no problem at all

> Initialising tasks: 100% |######################################################################################################################| Time: 0:00:04
Sstate summary: Wanted 417 Local 366 Mirrors 0 Missed 51 Current 2613 (87% match, 98% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 7226 tasks of which 7124 didn't need to be rerun and all succeeded.
raed@fairbird:~/build_image/DM920/openpli-dreambox-oe-core$

**Comment by elhawaryna** [comment]
Hi, I only have one device DM520 and I actually removed the folder and the same problem

**Comment by elhawaryna** [comment]
The construction process was completed after removing the entire build folder and rebuilding again. Thank you very much
