### ISSUE TITLE
ERROR: spdlog

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#38]
https://www.mediafire.com/file/4284igbidnatvxk/20230223135054.zip/file

**Comment by fairbird** [comment]
I have updated core .... and already solved the issue yesterday
https://github.com/fairbird/openpli-dreambox-oe-core/commit/a82495926e814e3141b282a825d9607b3ef59161

As I said before for you Every time if I updated core you need to remove tmp or complete build directory ...

From yesterday to today I was built two images for DM520 and DM7080 ... 
But core need more test from me ... wait until I finished

**Comment by elhawaryna** [comment]
I built only 820 images, not its feed, and the installation was done without problems, as well as the speed of the operation process, and I really did what you preferred regarding the temp folder
Thank you dear brother

**Comment by fairbird** [comment]
Now the core is stable no problem with build images ... Do you still have any issues ?! If not please close this isse !!
