### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#40]
https://www.mediafire.com/file/wnt2p9w8uffrwoh/20230327162450.zip/file

**Comment by fairbird** [comment]
Please try again after this commit ..
https://github.com/fairbird/openpli-dreambox-oe-core/commit/e1c1866ad9477c64bb7d834bf76b6563e54a3224

**Comment by fairbird** [comment]
Solved !! Please try gain ..
https://github.com/fairbird/openpli-dreambox-oe-core/commit/7756e057e36c293adc08480359aec4684adf3b60

**Comment by elhawaryna** [comment]
All right, thank you very much
