### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by NicZ1** [fairbird/openpli-dreambox-oe-core#43]
Since this morning I have started to receive this error:

ERROR: No recipes in default available for:
  /home/nic/openpli-dreambox-oe-core/meta-openpli/recipes-support/fmt/fmt_10.%.bbappend

I have even re-installed Ubuntu from scratch to try to fix it.

thanks

**Comment by NicZ1** [comment]
I have deleted the folder (moved somewhere safe) and it started working. Let's see how far it goes.

**Comment by Hains** [comment]
@fairbird  You need to update the meta-openembedded submodule. That update contains version 10 of fmt which matches with the bbappend. 
Update also needed for latest wavpack, required to build latest MPD.

**Comment by Hains** [comment]
@NicZ1 In the meantime it can be fixed with:

cd meta-openembedded
git pull origin master
cd ..

**Comment by NicZ1** [comment]
I will try that!!! Many thanks for replying.

(this is my first build so please forgive if I state the obvious sometimes)

**Comment by Hains** [comment]
That's OK.
Next time better to report directly and wait some time, instead of re-installing OS.
That's pity of the work, time and energy  :)

**Comment by fairbird** [comment]
> @fairbird You need to update the meta-openembedded submodule. That update contains version 10 of fmt which matches with the bbappend. Update also needed for latest wavpack, required to build latest MPD.

I don't have time to update and check oe-core (I will update it tonight) 
Thank you

**Comment by fairbird** [comment]
Update OE-core
https://github.com/fairbird/openpli-dreambox-oe-core/commit/16d1c18babde1c57e05fce6ec1b8bb4cc47e1227
