### ISSUE TITLE
ERROR: blindscan.patch

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#45]
ERROR: enigma2-plugins-y-gitAUTOINC+98b81efe97-r0 do_patch: Applying patch 'remove-other-type-from-blindscan.patch' on target directory '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugins/y-gitAUTOINC+98b81efe97-r0/git'
CmdError('quilt --quiltrc /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugins/y-gitAUTOINC+98b81efe97-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch remove-other-type-from-blindscan.patch
patching file blindscan/src/plugin.py
Hunk #1 FAILED at 1798.
1 out of 1 hunk FAILED -- rejects in file blindscan/src/plugin.py
Patch remove-other-type-from-blindscan.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugins/y-gitAUTOINC+98b81efe97-r0/temp/log.do_patch.647268
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3547 tasks of which 1812 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins.bb:do_patch
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by fairbird** [comment]
https://github.com/fairbird/openpli-dreambox-oe-core/commit/f47d5427379718996ec4acfc4635acc2c8a709ce
