### ISSUE TITLE
Building for DreamOne

### ISSUE THREAD

**Issue by mihaip1948** [fairbird/openpli-dreambox-oe-core#48]
Build exit with error ... not finding in path : curl python python2
I've installed with "sudo apt install" curl and python but "no candidate" for python !!!

**Comment by fairbird** [comment]
Please follow setups one by one here
https://github.com/fairbird/openpli-dreambox-oe-core#depend-on-python-3
and install all packages
https://github.com/fairbird/openpli-dreambox-oe-core#dependencies
and use ubuntu 22.04 or 22.10 or 23.04

P.s: As I mentioned here (DreamOne/Two not ready yet (Audio issue)))
https://github.com/fairbird/openpli-dreambox-oe-core#depend-on-python-3

**Comment by mihaip1948** [comment]
Thanks for the answer !!! All done by the book ! Commands were copied ... line by line from a file
and pasted into Terminal ! all executed without error till ... build script !!!
I've used Ubuntu LTS 22.04 installed into his own partition on a i7 with 16 Gb RAM.

`/bin/bash

sudo apt install -y autoconf automake bison bzip2 cvs diffstat flex g++ g++-multilib gawk gcc gettext git git-lfs gzip help2man ncurses-bin libncurses5-dev libc6-dev libtool lz4 liblz4-tool make texinfo patch perl pkg-config subversion tar texi2html wget chrpath libxml2-utils xsltproc python3-setuptools libc6 genromfs mtd-utils dpkg-dev sshpass poedit translate-toolkit xclip linux-firmware linux-headers-`uname -r` linux-headers-`uname -r` linux-image-`uname -r` linux-tools-`uname -r` linux-libc-dev linux-source u-boot-tools upx-ucl doxygen optipng libglib2.0-dev pngquant default-jdk fastboot adb libssl-dev libc6-dev-i386 lib32z1 m4 intltool ccache zlib1g zlib1g-dev liblzo2-dev tcl dpkg asciidoc texlive-latex-base dblatex xutils-dev gparted openssh-server nfs-common nfs-kernel-server lintian git-doc git-gui gitk indent tofrodos fakeroot meld atftpd sharutils manpages-dev manpages-posix manpages-posix-dev libgdk-pixbuf2.0-dev linux-doc build-essential socat libsdl1.2-dev xterm gcc-multilib libopenmpi-dev parted mercurial binutils imagemagick librsvg2-bin jq linux-libc-dev:i386 linux-headers-generic python3-pip python3-autopep8 python3-six python3-six libnl-3-dev libimage-exiftool-perl dos2unix ffmpeg dialog default-jre libc6-i386 quilt zstd lib32tinfo6 guile-2.2-libs lib32ncurses6 lib32ncursesw6 lib32ncurses-dev

sudo dpkg-reconfigure dash

git clone https://github.com/fairbird/openpli-dreambox-oe-core.git

cd openpli-dreambox-oe-core

./build_image.sh

**...
Cloning into '/openpli-dreambox-oe-core/openembedded-core'...
Submodule path 'bitbake': checked out '6abdc81dec06a362bfbcc06d69b90b96bd9bef01'
Submodule path 'meta-openembedded': checked out '1955d0f140a9610346021d42fa45cb186eb6f042'
Submodule path 'meta-qt6': checked out '8b9d5c95caa4f179b54eb94f5feabcb45af3a280'
Submodule path 'openembedded-core': checked out 'f7ed7ae854e49276750d1895593e0a2033714235'
The openpli OE is now up-to-date.
Generating /openpli-dreambox-oe-core/build/env.source
Generating /openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /openpli-dreambox-oe-core/build/conf/local.conf
Building image for dreamone
check internet connection: Online      
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  python
make: *** [Makefile:109: image] Error 1`**

When was RUN first time  ... the error was referring:  python python2 and curl !
I've installed them by : sudo apt install ... but there is no candidate for
"python" ! I've even try to declare an alias ... python='python2" ... was
recognized but the error message ... persists !!! The message is not specific
to dreamone ! I've tried to build dm900 and dm920 ... same message !

Probably on your distribution the referred packages were already defined
outside ! and must be added to the "apt install" list !!! The problem remains
"python" !!!

The fact that for ONE and TWO have still some audio issues is not relevant !
 for me the journey to assist the birth ... matters !!! I'm an old horse !!!

**Comment by fairbird** [comment]
Is this first time to build image ?!!
If yes then you need to read this carefully !!!
https://wiki.openpli.org/Information_for_Developers

**Comment by mihaip1948** [comment]
I must admit ... YES ! the build environment is as you wrote ! but
from TOOLS ... "python" is missing ! Why ? this is a mistery !
I fake it ! and the build image is started !!! Probably nobody
need .. python !

**Comment by fairbird** [comment]
Did you read What I wrote ?!!
My source depend on python3 **NOT PYTHON2** ...
Please follow what I wrote before ... Try to use ubuntu 22.04 or 22.10 or 23.04 !!!

Do this seteps

> sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
sudo update-alternatives --config python

select python3 not python2

**Comment by mihaip1948** [comment]
I'll do it !!!
I've know you build depends on python3 !!! not python2
or python1 !!! but somewhere , outside your sources , there
is a reference to simply "python" !!! I've trick it and build started !

The build for DreamONE took some 2 hours an finally failed !
I know ! you've warned me ... there are still problems !!! this
is dome part of the log ...

> **ed/dreamone/kernel-source/fs/binfmt_misc.c:13:
| In function 'check_object_size',
|     inlined from 'copy_from_user' at /home/mihai/openpli-dreambox-oe-core/build/tmp/work-shared/dreamone/kernel-source/arch/arm64/include/asm/uaccess.h:448:3,
|     inlined from 'parse_command' at /home/mihai/openpli-dreambox-oe-core/build/tmp/work-shared/dreamone/kernel-source/fs/binfmt_misc.c:527:6:
| /home/mihai/openpli-dreambox-oe-core/build/tmp/work-shared/dreamone/kernel-source/include/linux/thread_info.h:96:17: warning: 's' may be used uninitialized [-Wmaybe-uninitialized]
|    96 |                 __check_object_size(ptr, n, to_user);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/mihai/openpli-dreambox-oe-core/build/tmp/work-shared/dreamone/kernel-source/include/linux/thread_info.h: In function 'parse_command':
| /home/mihai/openpli-dreambox-oe-core/build/tmp/work-shared/dreamone/kernel-source/include/linux/thread_info.h:89:13: note: by argument 1 of type 'const void *' to '__check_object_size' declared here
|    89 | extern void __check_object_size(const void *ptr, unsigned long n,
|       |             ^~~~~~~~~~~~~~~~~~~
| /home/mihai/openpli-dreambox-oe-core/build/tmp/work-shared/dreamone/kernel-source/fs/binfmt_misc.c:523:14: note: 's' declared here
|   523 |         char s[4];
|       |              ^
|   CC      fs/binfmt_script.o
|   CC      fs/ubifs/commit.o
|   CC      fs/ubifs/gc.o
ne 292
| 	#3: oe_runmake, /home/mihai/openpli-dreambox-oe-core/build/tmp/work/dreamone-oe-linux/linux-meson64/1_4.9.113-643176-g72b0573-.1/temp/run.do_compile.1038660, line 220
| 	#4: kernel_do_compile, /home/mihai/openpli-dreambox-oe-core/build/tmp/work/dreamone-oe-linux/linux-meson64/1_4.9.113-643176-g72b0573-.1/temp/run.do_compile.1038660, line 204
| 	#5: do_compile, /home/mihai/openpli-dreambox-oe-core/build/tmp/work/dreamone-oe-linux/linux-meson64/1_4.9.113-643176-g72b0573-.1/temp/run.do_compile.1038660, line 150
| 	#6: main, /home/mihai/openpli-dreambox-oe-core/build/tmp/work/dreamone-oe-linux/linux-meson64/1_4.9.113-643176-g72b0573-.1/temp/run.do_compile.1038660, line 312
ERROR: Task (/home/mihai/openpli-dreambox-oe-core/meta-dreambox/recipes-linux/linux-meson64_4.9.113-643176-g72b0573.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4083 tasks of which 0 didn't need to be rerun and 1 failed.
Summary: 1 task failed:
  /home/mihai/openpli-dreambox-oe-core/meta-dreambox/recipes-linux/linux-meson64_4.9.113-643176-g72b0573.bb:do_compile
Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Error 1
mihai@mihai-ThinkPad-X1-Carbon-6th:~/openpli-dreambox-oe-core$**

**Comment by fairbird** [comment]
-The time to compile and build image around 2 to 6 hours depend on pc features (Ram + CPU)

I will start now to build image for dreamtwo and I will see if there is error or not on my Ubuntu 23.04 !!

**Comment by mihaip1948** [comment]
I didn't dare ! Please keep us informed !!!

**Comment by mihaip1948** [comment]
I have Ubuntu 22.04 ! but will be very interesting to see how you will  build on a new installed system as is mine  !!!

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/0ebcfc92c4fde535dead74b654dfc285cf4ac180

-Remove tmp folder from build directory
-Then build image again

From my side I finish to build an image for DreamTwo ...
Here if you want to test it (No support just for test)
https://www.mediafire.com/file/24puj649ly2hafr/openpli-enigma2-GCC-13.1-dreamtwo.rootfs.tar.bz2/file

**Comment by mihaip1948** [comment]
Well tanks ! but I have Dream ONE !!! if you build for Dream ONE ... gladly !!!
I'll try myself to build for ONE but if you can ... make one ! For test ... of course !!!

The image for TWO will not work on ONE ! different Kernel and dtb !

**Comment by mihaip1948** [comment]
Congratulations !!! the build was successful !
The image is pretty decent ! except the audio !
https://mega.nz/file/KxEAnByb#DGaVAM1QtPDnwvMJvJhpJs7EjFDhU43x677kUXTbMWE

**Comment by fairbird** [comment]
So the issue solved !!

**Comment by mihaip1948** [comment]
I-ve installed this Oscam Emu ... 
https://mega.nz/file/z5UjTZII#fMJNF57J6g69O-TrfUK4vYfa5xpMEY9MF3V50eqjT-4

    Pe miercuri, 14 iunie 2023 la 11:07:58 EEST, RAED ***@***.***> a scris:  
 
 


So the issue solved !!

**Comment by fairbird** [comment]
As I said no support for image on source ... Here just for compile issues ...

**Comment by mihaip1948** [comment]
Missing audioa is not an issue ... is a protection !Audio sync is closed source ! if you have it ... youwill have the audio also !

**Comment by fairbird** [comment]
Yes I know it is CLOSED source .. And I don't have it !!!
