### ISSUE TITLE
dm800se

### ISSUE THREAD

**Issue by NSS-SAT** [fairbird/openpli-dreambox-oe-core#5]
hi friend then I tried 800se 500hd in multiboot and it goes great but it has a problem it does not detect the network and not even the wifi when switching on driver network lan out we can do something thanks

**Comment by fairbird** [comment]
I need to build and test DM800se images first and then will be see if there are some issues or not !!!

**Comment by fairbird** [comment]
There is not problem at all in image ... as screenshots shown ...
I really don't know why all these problems appear to you in your building in different forms for different devices...and there are basically no such problems, only you have them appear..

![3](https://user-images.githubusercontent.com/1761779/145244438-cea0b8e5-65b0-4526-ac6a-732b1496df1f.jpg)

![2](https://user-images.githubusercontent.com/1761779/145244433-7c9d2af1-1eec-425a-8e00-33655cdd39b9.jpg)
