### ISSUE TITLE
ERROR backupsuite

### ISSUE THREAD

**Issue by atefganm** [fairbird/openpli-dreambox-oe-core#50]
`Build Configuration:
BB_VERSION           = "2.4.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "linuxmint-21.1"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-13.1"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
SOC_FAMILY           = "bcm7435"
RCTYPE               = "0"
RCNAME               = "dmm2"
RCIDNUM              = "2"
DEVELOPER_NAME       = "openpli"
DISTRO_FEED_URI      = "http://atef-ganm/feeds/openpli-GCC-13.1"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:1955d0f140a9610346021d42fa45cb186eb6f042"
meta                 = "HEAD:f7ed7ae854e49276750d1895593e0a2033714235"
meta-openpli         
meta-dreambox        = "develop:1128c13c15d676f4e8f39f07222ef2b25bebf4c8"
meta-qt6             = "HEAD:8b9d5c95caa4f179b54eb94f5feabcb45af3a280"

Initialising tasks: 100% |#####################################################################################################################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 2026 Local 1212 Mirrors 0 Missed 814 Current 3403 (59% match, 85% complete)
Removing 5 stale sstate objects for arch dm820: 100% |#########################################################################################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
ERROR: enigma2-plugin-extensions-backupsuite-gitAUTOINC+0255c1b500-r0 do_patch: Applying patch 'use-pyc-instead-of-pyo.patch' on target directory '/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupsuite/gitAUTOINC+0255c1b500-r0/git'
CmdError('quilt --quiltrc /home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupsuite/gitAUTOINC+0255c1b500-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch use-pyc-instead-of-pyo.patch
patching file plugin/backupdmm.sh
Hunk #1 FAILED at 307.
1 out of 1 hunk FAILED -- rejects in file plugin/backupdmm.sh
patching file plugin/backuphdd-dmm.sh
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- rejects in file plugin/backuphdd-dmm.sh
patching file plugin/backuphdd.sh
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- rejects in file plugin/backuphdd.sh
patching file plugin/backupmmc-dmm.sh
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- rejects in file plugin/backupmmc-dmm.sh
patching file plugin/backupmmc.sh
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- rejects in file plugin/backupmmc.sh
patching file plugin/backupsuite.sh
Hunk #1 FAILED at 386.
1 out of 1 hunk FAILED -- rejects in file plugin/backupsuite.sh
patching file plugin/backupusb-dmm.sh
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- rejects in file plugin/backupusb-dmm.sh
patching file plugin/backupusb.sh
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- rejects in file plugin/backupusb.sh
patching file plugin/whatsnew.txt
Hunk #1 succeeded at 91 (offset 3 lines).
Patch use-pyc-instead-of-pyo.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-backupsuite/gitAUTOINC+0255c1b500-r0/temp/log.do_patch.541868
ERROR: Task (/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupsuite.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 10668 tasks of which 10460 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupsuite.bb:do_patch
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
atef@atef-ganm:~/fairbird-OpenPli/openpli-dreambox-oe-core$ 
`

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/3e7c0c710ec8f9a8f324f1c0c5cc40ef8b65b0e4
