### ISSUE TITLE
Please amend, thanks

### ISSUE THREAD

**Issue by atefganm** [fairbird/openpli-dreambox-oe-core#51]
https://github.com/OpenPLi/openpli-oe-core/commit/9437d76b4a638d97bccb4352ee9d543588faf121

`Build Configuration:
BB_VERSION           = "2.4.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "linuxmint-21.1"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-13.1"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
SOC_FAMILY           = "bcm7435"
RCTYPE               = "0"
RCNAME               = "dmm2"
RCIDNUM              = "2"
DEVELOPER_NAME       = "openpli"
DISTRO_FEED_URI      = "http://atef-ganm/feeds/openpli-GCC-13.1"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:1955d0f140a9610346021d42fa45cb186eb6f042"
meta                 = "HEAD:f7ed7ae854e49276750d1895593e0a2033714235"
meta-openpli         
meta-dreambox        = "develop:e71a91d8f15d5b8a4ea8798f926963e4148c1308"
meta-qt6             = "HEAD:8b9d5c95caa4f179b54eb94f5feabcb45af3a280"

Initialising tasks: 100% |#####################################################################################################################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 2006 Local 1224 Mirrors 0 Missed 782 Current 3423 (61% match, 85% complete)
Removing 13 stale sstate objects for arch dm820: 100% |########################################################################################################################################################################################| Time: 0:00:00
Removing 2 stale sstate objects for arch mips32el: 100% |######################################################################################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
WARNING: openresolv-3.5.2-r0 do_fetch: Failed to fetch URL http://roy.marples.name/downloads/openresolv/openresolv-3.5.2.tar.bz2, attempting MIRRORS if available
ERROR: openresolv-3.5.2-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="3014"; export SSH_AUTH_SOCK="/tmp/ssh-XXXXXX4LJrKg/agent.3013"; export PATH="/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/openembedded-core/scripts:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/recipe-sysroot-native/usr/bin/allarch-oe-linux:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/recipe-sysroot/usr/bin/crossscripts:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/recipe-sysroot-native/usr/sbin:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/recipe-sysroot-native/usr/bin:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/recipe-sysroot-native/sbin:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/recipe-sysroot-native/bin:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/bitbake/bin:/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/atef"; /usr/bin/env wget -t 2 -T 30 --passive-ftp -O /home/atef/openpli-dreambox-oe-core/openpli-dreambox-oe-core/sources/openresolv-3.5.2.tar.bz2.tmp -P /home/atef/openpli-dreambox-oe-core/openpli-dreambox-oe-core/sources 'http://roy.marples.name/downloads/openresolv/openresolv-3.5.2.tar.bz2' --progress=dot -v failed with exit code 8, no output
ERROR: openresolv-3.5.2-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://roy.marples.name/downloads/openresolv/openresolv-3.5.2.tar.bz2')
ERROR: Logfile of failure stored in: /home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/openresolv/3.5.2-r0/temp/log.do_fetch.20426
ERROR: Task (/home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/meta-openpli/recipes-connectivity/openresolv/openresolv_3.5.2.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9887 tasks of which 9787 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/fairbird-OpenPli/openpli-dreambox-oe-core/meta-openpli/recipes-connectivity/openresolv/openresolv_3.5.2.bb:do_fetch
Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
atef@atef-ganm:~/fairbird-OpenPli/openpli-dreambox-oe-core$ 
`

**Comment by fairbird** [comment]
Update !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/1379c04dd4627c82546e808927a01f115cb54c00

Please if you solved your issue .. close it !
https://github.com/fairbird/openpli-dreambox-oe-core/issues/50
