### ISSUE TITLE
Missing or false Packets

### ISSUE THREAD

**Issue by Token2K** [fairbird/openpli-dreambox-oe-core#53]
@fairbird
First of all, thanks for your Openpli tutorial.
following things I noticed - starting from a virgin Ubuntu 23.04!
1. the package "linux-libc-dev:i386" does not exist -> this is now called "linux-libc-dev-i386-cross"!
2. in Ubuntu 23.04 there is no more Phyton2 as a package -> but your compile instructions in the Ubuntu forum helped here.

=> would be useful here still a suitable addition in the read.me

**Comment by fairbird** [comment]
No problem on Ubuntu 23.04

> raed@fairbird:~$ sudo apt install linux-libc-dev:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  linux-libc-dev:i386
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 1,557 kB of archives.
After this operation, 6,994 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu lunar-updates/main i386 linux-libc-dev i386 6.2.0-27.28 [1,557 kB]
Fetched 1,557 kB in 2s (789 kB/s)              
Selecting previously unselected package linux-libc-dev:i386.
(Reading database ... 356911 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_6.2.0-27.28_i386.deb ...
Unpacking linux-libc-dev:i386 (6.2.0-27.28) ...
Setting up linux-libc-dev:i386 (6.2.0-27.28) ...

But any way the package no need it any more REMOVED!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/2f0c4bd16d4a8b1832fe77d7067b9e0393ff93ae
