### ISSUE TITLE
dreamone

### ISSUE THREAD

**Issue by NSS-SAT** [fairbird/openpli-dreambox-oe-core#6]
so sorry friend I'm trying to test your work and it seems that everything is going but the one does not go up I am [](url)https://i.postimg.cc/P5XthDZ4/dmone.png

dreamone

**Comment by NSS-SAT** [comment]
created all original as you developed your work

**Comment by fairbird** [comment]
As I wrote in ReadMe file (DreamOne/Two not ready yet (Audio issue)) ..
I cannot support DreamOne/Two (No open source, No patches Available, No Help from Multimedia Test) Also I don't have devices.

**Comment by NSS-SAT** [comment]
flash invalide image--d-jou need a DM7020v2Il 11 Dic 2021 15:49, RAED ***@***.***> ha scritto:
As I wrote in ReadMe file (DreamOne/Two not ready yet (Audio issue)) ..
I cannot support DreamOne/Two (No open source, No patches Available and I don't have devices)

**Comment by fairbird** [comment]
I'm 90% sure You have some wrong in your building image ....
Always you have some issues that never have been happening with us ..
Make sure from your distro (are using using Ubuntu ?!) What version is ?!

P/s I was built test image for DreamOne to some friend to test it and the image flashed and worked without any error. Just (Audio issue) Style did not find way to fix it.

**Comment by NSS-SAT** [comment]
so i'm trying somehow to test all your work and i use ubuntu 20 and i compiled the whole original but i don't understand these errors i just want to put you in the light of everything and i don't want to stress you sorryIl 13 Dic 2021 21:23, RAED ***@***.***> ha scritto:
I'm 90% sure You have some wrong in your building image ....
Always you have some issues that never have been happening with us ..
Make sure from your distro (are using using Ubuntu ?!) What version is ?!
P/s I was built test image for DreamOne to some friend to test it and the image flashed and worked without any error. Just (Audio issue) Style did not find way to fix it.

**Comment by fairbird** [comment]
Thank you for feedback ... But I can not test all images. Because just I have DM800, DM800se and DM920 devices...

**Comment by NSS-SAT** [comment]
thank you very much buddy I personally have tested with all the added libraries dm 525 ... 900 and 800se in multiboot with additions of libraries does not see network without additions it is great ... I have no way to test 7080..500hdv2..7020 instead they tried it last night and they say that img does not go up I will continue to support your project which I think is a great job congratulationsIl 14 Dic 2021 11:02, RAED ***@***.***> ha scritto:
Thank you for feedback ... But I can not test all images. Because just I have DM800, DM800se and DM920 devices...

**Comment by NSS-SAT** [comment]
hi buddy sorry we have a way to do 7020v2 thanks

**Comment by Torros-Team** [comment]
hi friend i'm trying to compile for a DM800se with your openpli-dreambox-oe-core and when it reaches 40% it gives me this error can you tell me what I can do thanks:

ERROR: transmission-3.00-r0 do_fetch: Fetcher failure: Unable to find revision bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd in branch master even from upstream
ERROR: transmission-3.00-r0 do_fetch: Fetcher failure for URL: 'gitsm: //github.com/transmission/transmission'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/elcobra/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/transmission/3.00-r0/temp/log.do_fetch.3239951
ERROR: Task (/home/elcobra/Musica/openpli-dreambox-oe-core/meta-openembedded/meta-oe/recipes-connectivity/transmission/transmission_git.bb:do_fetch) failed with exit code '1'
