### ISSUE TITLE
dreambox-enigma2-config SRC_URI entry skin_box.xml

### ISSUE THREAD

**Issue by open-cobralibero** [fairbird/openpli-dreambox-oe-core#66]
torres@torres-Nitro-AN517-54:~/openpli-dreambox-oe-core$ MACHINE=dm7020hd make image
[ -d /home/torres/openpli-dreambox-oe-core/meta-openembedded/meta-oe ] || make  update
make[1]: ingresso nella directory «/home/torres/openpli-dreambox-oe-core»
Updating Git repositories...
Già aggiornato.
Sottomodulo 'bitbake' (git://git.openembedded.org/bitbake) registrato per il percorso 'bitbake'
Sottomodulo 'meta-openembedded' (git://git.openembedded.org/meta-openembedded) registrato per il percorso 'meta-openembedded'
Sottomodulo 'meta-qt6' (git://code.qt.io/yocto/meta-qt6.git) registrato per il percorso 'meta-qt6'
Sottomodulo 'openembedded-core' (git://git.openembedded.org/openembedded-core) registrato per il percorso 'openembedded-core'
Clone in '/home/torres/openpli-dreambox-oe-core/bitbake' in corso...
Clone in '/home/torres/openpli-dreambox-oe-core/meta-openembedded' in corso...
Clone in '/home/torres/openpli-dreambox-oe-core/meta-qt6' in corso...
Clone in '/home/torres/openpli-dreambox-oe-core/openembedded-core' in corso...
Percorso del sottomodulo 'bitbake': eseguito checkout di '5625849e9327fc71a38eea00d4506f80abc11bc6'
Percorso del sottomodulo 'meta-openembedded': eseguito checkout di '05e32934d064daa186742084586b3111036a8e1b'
Percorso del sottomodulo 'meta-qt6': eseguito checkout di '437af2514a4cd205c998d11fc58e3bb638083b44'
Percorso del sottomodulo 'openembedded-core': eseguito checkout di '67c287c8131c7e896f6992d32a26d097cbd6414e'
The openpli OE is now up-to-date.
make[1]: uscita dalla directory «/home/torres/openpli-dreambox-oe-core»
Generating /home/torres/openpli-dreambox-oe-core/build/env.source
Generating /home/torres/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/torres/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/torres/openpli-dreambox-oe-core/build/conf/local.conf
Building image for dm7020hd
check internet connection: Online      
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |                                                                                                                                                                              | ETA:  --:--:--
Loaded 0 entries from dependency cache.
ERROR: /home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config.bb: Unable to get checksum for dreambox-enigma2-config SRC_URI entry skin_box.xml: file could not be found:  0:00:15
The following paths were searched:
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/openpli/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/openpli/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/openpli/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/dm7020hd/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/dm7020hd/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/dm7020hd/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/bcm7405/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/bcm7405/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/bcm7405/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/mipsarcho32el/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/mipsarcho32el/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/mipsarcho32el/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/mipsarcho32/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/mipsarcho32/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/mipsarcho32/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/mipsarchel/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/mipsarchel/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/mipsarchel/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/mipsarch/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/mipsarch/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/mipsarch/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/mipsel/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/mipsel/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/mipsel/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config-1.0/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/dreambox-enigma2-config/skin_box.xml
/home/torres/openpli-dreambox-oe-core/meta-dreambox/recipes-bsp/files/skin_box.xml
ERROR: Parsing halted due to errors, see error messages above

Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Errore 1
torres@torres-Nitro-AN517-54:~/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Please try again ..
https://github.com/fairbird/openpli-dreambox-oe-core/commit/9c3db6a12e263cf29fc6fec797f9f18219222704

**Comment by open-cobralibero** [comment]
hi fairbird thanks it seems to be going well at the moment

**Comment by open-cobralibero** [comment]
Good morning fairbird pultroop from another error now.

torres@torres-Nitro-AN517-54:~/Documenti/core/openpli-dreambox-oe-core$  MACHINE=dm7020hd make image
Building image for dm7020hd
check internet connection: Online      
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
Loading cache: 100% |###############################################################################################################################################################################| Time: 0:00:00
Loaded 4971 entries from dependency cache.
Parsing recipes: 100% |#############################################################################################################################################################################| Time: 0:00:09
Parsing of 3474 .bb files complete (3174 cached, 300 parsed). 5271 targets, 674 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync

Build Configuration:
BB_VERSION           = "2.4.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm7020hd"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-13.2"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
SOC_FAMILY           = "bcm7405"
RCTYPE               = "0"
RCNAME               = "dmm2"
RCIDNUM              = "2"
DISTRO_FEED_URI      = "http://torres-Nitro-AN517-54/feeds/openpli-GCC-13.2"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:05e32934d064daa186742084586b3111036a8e1b"
meta                 = "HEAD:67c287c8131c7e896f6992d32a26d097cbd6414e"
meta-openpli         
meta-dreambox        = "develop:28ed4759367f4f8fecf4d62e101ab2ce757e485e"
meta-qt6             = "HEAD:437af2514a4cd205c998d11fc58e3bb638083b44"

Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:02
Sstate summary: Wanted 1897 Local 0 Mirrors 0 Missed 1897 Current 1180 (0% match, 38% complete)
NOTE: Executing Tasks
WARNING: replex-0.1.6.8-r0 do_fetch: Failed to fetch URL http://repository.slacky.eu/slackware-12.2/multimedia/replex/0.1.6.8/src/replex-0.1.6.8.tar.gz, attempting MIRRORS if available
ERROR: replex-0.1.6.8-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1574"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/torres/Documenti/core/openpli-dreambox-oe-core/openembedded-core/scripts:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/recipe-sysroot/usr/bin/crossscripts:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/recipe-sysroot-native/usr/sbin:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/recipe-sysroot-native/usr/bin:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/recipe-sysroot-native/sbin:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/recipe-sysroot-native/bin:/home/torres/Documenti/core/openpli-dreambox-oe-core/bitbake/bin:/home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/torres"; /usr/bin/env wget -t 2 -T 30 --passive-ftp -O /home/torres/Documenti/core/openpli-dreambox-oe-core/sources/replex-0.1.6.8.tar.gz.tmp -P /home/torres/Documenti/core/openpli-dreambox-oe-core/sources 'http://repository.slacky.eu/slackware-12.2/multimedia/replex/0.1.6.8/src/replex-0.1.6.8.tar.gz' --progress=dot -v failed with exit code 8, no output
ERROR: replex-0.1.6.8-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://repository.slacky.eu/slackware-12.2/multimedia/replex/0.1.6.8/src/replex-0.1.6.8.tar.gz')
ERROR: Logfile of failure stored in: /home/torres/Documenti/core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/replex/0.1.6.8/temp/log.do_fetch.672950
ERROR: Task (/home/torres/Documenti/core/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/replex/replex_0.1.6.8.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2838 tasks of which 2690 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/torres/Documenti/core/openpli-dreambox-oe-core/meta-openpli/recipes-multimedia/replex/replex_0.1.6.8.bb:do_fetch
Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/core/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/ee1d57e3c15ca26cb0f14b08396d6a08378a1c00

**Comment by open-cobralibero** [comment]
perfect now it's fine thank you very much
