### ISSUE TITLE
ERROR: ofgwrite-4.x+git-r0 do_compile: oe_runmake failed

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#68]
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-extended/ofgwrite/ofgwrite.bb:do_compile) failed with exit code '1'

https://www.mediafire.com/file/n7ii5a6s8rgm01l/20230926151132.log.zip/file

**Comment by fairbird** [comment]
You need to delete tmp folder .. or .. clean sstate-cache of ofgwrite

> cd build
source env.sourece
MACHINE=dm820 -c clean -f ofgwrite

Then start again to build image ...
