### ISSUE TITLE
ERROR: enigma2-plugins-alliance-gitr-r1 do_patch

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#69]
ERROR: enigma2-plugins-alliance-gitr-r1 do_patch: Applying patch 'remove-duplicate-plugins-with-pli-plugins.patch' on target directory '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugins-alliance/gitr/git'
CmdError('quilt --quiltrc /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugins-alliance/gitr/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch remove-duplicate-plugins-with-pli-plugins.patch
patching file Makefile.am
Hunk #2 succeeded at 12 (offset 20 lines).
Hunk #3 succeeded at 30 (offset 20 lines).
Hunk #4 FAILED at 27.
1 out of 4 hunks FAILED -- rejects in file Makefile.am
Patch remove-duplicate-plugins-with-pli-plugins.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugins-alliance/gitr/temp/log.do_patch.1081636
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 12598 tasks of which 12520 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins-alliance.bb:do_patch
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by fairbird** [comment]
Update patch....
https://github.com/fairbird/openpli-dreambox-oe-core/commit/382d411b2ee90c8d1f9028d1266ea6fff2e9d7cb

Please do nor forget to close any issue you was open it and solved like
https://github.com/fairbird/openpli-dreambox-oe-core/issues/68
