### ISSUE TITLE
oscam

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#70]
ERROR: enigma2-plugin-softcams-oscam-emu-1.20+git-r0 do_patch: Applying patch 'icam.patch' on target directory '/home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-softcams-oscam-emu/1.20+git/git'
CmdError('quilt --quiltrc /home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-softcams-oscam-emu/1.20+git/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch icam.patch
patching file CMakeLists.txt
Hunk #1 FAILED at 684.
1 out of 1 hunk FAILED -- rejects in file CMakeLists.txt
patching file Makefile
Hunk #1 FAILED at 58.
Hunk #2 FAILED at 68.
Hunk #3 succeeded at 295 (offset 8 lines).
Hunk #4 FAILED at 450.
3 out of 4 hunks FAILED -- rejects in file Makefile
patching file config.h
Hunk #1 FAILED at 3.
Hunk #2 FAILED at 33.
2 out of 2 hunks FAILED -- rejects in file config.h
patching file config.sh
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 28.
Hunk #3 FAILED at 475.
3 out of 3 hunks FAILED -- rejects in file config.sh
patching file ffdecsa/CMakeLists.txt
Hunk #1 succeeded at 16 with fuzz 2 (offset 11 lines).
patching file ffdecsa/ffdecsa.c
Hunk #1 FAILED at 24.
Hunk #2 FAILED at 53.
Hunk #3 FAILED at 61.
Hunk #4 FAILED at 107.
Hunk #5 succeeded at 380 (offset 102 lines).
Hunk #6 FAILED at 485.
Hunk #7 FAILED at 566.
Hunk #8 succeeded at 772 (offset 130 lines).
Hunk #9 FAILED at 679.
7 out of 9 hunks FAILED -- rejects in file ffdecsa/ffdecsa.c
patching file ffdecsa/ffdecsa.h
Hunk #1 FAILED at 47.
1 out of 1 hunk FAILED -- rejects in file ffdecsa/ffdecsa.h
The next patch would create the file ffdecsa/parallel_128_neon.h,
which already exists!  Applying it anyway.
patching file ffdecsa/parallel_128_neon.h
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file ffdecsa/parallel_128_neon.h
patching file module-dvbapi.c
Hunk #1 FAILED at 11.
Hunk #2 FAILED at 7847.
2 out of 2 hunks FAILED -- rejects in file module-dvbapi.c
The next patch would create the file module-emulator-icam.c,
which already exists!  Applying it anyway.
patching file module-emulator-icam.c
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file module-emulator-icam.c
The next patch would create the file module-emulator-icam.h,
which already exists!  Applying it anyway.
patching file module-emulator-icam.h
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file module-emulator-icam.h
patching file module-emulator-streamserver.c
Hunk #1 succeeded at 10 with fuzz 2 (offset 1 line).
Hunk #2 FAILED at 379.
Hunk #3 FAILED at 538.
Hunk #4 succeeded at 1316 with fuzz 1 (offset 85 lines).
Hunk #5 FAILED at 1320.
Hunk #6 succeeded at 1441 with fuzz 2 (offset 78 lines).
Hunk #7 succeeded at 1494 with fuzz 2 (offset 81 lines).
Hunk #8 FAILED at 1538.
Hunk #9 succeeded at 1737 with fuzz 2 (offset 107 lines).
Hunk #10 FAILED at 1678.
Hunk #11 FAILED at 1893.
6 out of 11 hunks FAILED -- rejects in file module-emulator-streamserver.c
patching file module-emulator-streamserver.h
Hunk #1 FAILED at 18.
Hunk #2 FAILED at 84.
2 out of 2 hunks FAILED -- rejects in file module-emulator-streamserver.h
patching file module-radegast.c
Hunk #1 FAILED at 7.
Hunk #2 FAILED at 86.
2 out of 2 hunks FAILED -- rejects in file module-radegast.c
patching file oscam.c
Hunk #2 FAILED at 424.
1 out of 2 hunks FAILED -- rejects in file oscam.c
Patch icam.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /home/elhawary/Desktop/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugin-softcams-oscam-emu/1.20+git/temp/log.do_patch.199577
ERROR: Task (/home/elhawary/Desktop/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-softcams/enigma2-plugin-softcams-oscam-emu.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9687 tasks of which 9117 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/Desktop/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-softcams/enigma2-plugin-softcams-oscam-emu.bb:do_patch
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/Desktop/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
You are using old files !!
You need to update core .. 
Already I have removed ( icam.patch) before 4 days ago !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/1115384fa1c6b4709752df81dd3e74efb5c80277
