### ISSUE TITLE
enigma2-plugin-extensions-epgimport-rytec.bb

### ISSUE THREAD

**Issue by open-cobralibero** [fairbird/openpli-dreambox-oe-core#71]
hi fairbird good evening I'm having this problem

Updating Git repositories...
Già aggiornato.
Sottomodulo 'bitbake' (git://git.openembedded.org/bitbake) registrato per il percorso 'bitbake'
Sottomodulo 'meta-openembedded' (git://git.openembedded.org/meta-openembedded) registrato per il percorso 'meta-openembedded'
Sottomodulo 'meta-qt6' (git://code.qt.io/yocto/meta-qt6.git) registrato per il percorso 'meta-qt6'
Sottomodulo 'openembedded-core' (git://git.openembedded.org/openembedded-core) registrato per il percorso 'openembedded-core'
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/bitbake' in corso...
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/meta-openembedded' in corso...
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/meta-qt6' in corso...
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core' in corso...
Percorso del sottomodulo 'bitbake': eseguito checkout di '595176d6be95a9c4718d3a40499d1eb576b535f5'
Percorso del sottomodulo 'meta-openembedded': eseguito checkout di '1b0154df7743a5291a65ff891ad3ecc35661dc9f'
Percorso del sottomodulo 'meta-qt6': eseguito checkout di 'f00bd7134e1e7b82811f4c10d14ec5d05967f8ae'
Percorso del sottomodulo 'openembedded-core': eseguito checkout di '40f2e5776ebf6cf93694d05189488e8448767b3a'
The openpli OE is now up-to-date.
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/env.source
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/local.conf
Building feed for dm820
check internet connection: Online      
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |                                           | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:06:25
Parsing of 3514 .bb files complete (0 cached, 3514 parsed). 5327 targets, 680 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync

Build Configuration:
BB_VERSION           = "2.6.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-13.2"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
SOC_FAMILY           = "bcm7435"
RCTYPE               = "0"
RCNAME               = "dmm2"
RCIDNUM              = "2"
DISTRO_FEED_URI      = "http://torres-Nitro-AN517-54/feeds/openpli-GCC-13.2"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:1b0154df7743a5291a65ff891ad3ecc35661dc9f"
meta                 = "HEAD:40f2e5776ebf6cf93694d05189488e8448767b3a"
meta-openpli         
meta-dreambox        = "develop:46dd320e2031a78457bbc9d6f350ea0e680fac5d"
meta-qt6             = "HEAD:f00bd7134e1e7b82811f4c10d14ec5d05967f8ae"

Initialising tasks: 100% |#######################################| Time: 0:00:19
Sstate summary: Wanted 8212 Local 0 Mirrors 0 Missed 8212 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
WARNING: libtirpc-native-1.3.3-r0 do_fetch: Failed to fetch URL https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.3.tar.bz2, attempting MIRRORS if available
WARNING: python3-daap-0.7.1-r2 do_fetch: Failed to fetch URL http://jerakeen.org/files/PythonDaap-0.7.1.tar.gz, attempting MIRRORS if available
WARNING: enigma2-plugin-extensions-epgimport-rytec-20230617-r0 do_fetch: Failed to fetch URL http://rytecepg.wanwizard.eu/rytec.sources.xml.20230617.gz, attempting MIRRORS if available
ERROR: enigma2-plugin-extensions-epgimport-rytec-20230617-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1509"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/bin/python3-native:/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core/scripts:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/bin/allarch-oe-linux:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot/usr/bin/crossscripts:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/sbin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/bin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/sbin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/bin:/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/bin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/torres"; /usr/bin/env wget -t 2 -T 30 --passive-ftp -O /home/torres/Documenti/openpli-dreambox-oe-core/sources/rytec.sources.xml.20230617.gz.tmp -P /home/torres/Documenti/openpli-dreambox-oe-core/sources 'http://rytecepg.wanwizard.eu/rytec.sources.xml.20230617.gz' --progress=dot -v failed with exit code 8, no output
ERROR: enigma2-plugin-extensions-epgimport-rytec-20230617-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://rytecepg.wanwizard.eu/rytec.sources.xml.20230617.gz')
ERROR: Logfile of failure stored in: /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/temp/log.do_fetch.1456123
ERROR: Task (/home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-epgimport-rytec.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3367 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-epgimport-rytec.bb:do_fetch
Summary: There were 3 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Fix it !
https://github.com/fairbird/openpli-dreambox-oe-core/commit/a1d8104264ebf55df86575dbc6f99cb80214f4b5

**Comment by open-cobralibero** [comment]
hi fairbird it's not working it's giving me another error now I've downloaded a new core

> Documenti/openpli-dreambox-oe-core$
 MACHINE=dm800se make image 
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/env.source
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/local.conf
Building image for dm800se
check internet connection: Online      
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |                                           | ETA:  --:--:--
Loaded 0 entries from dependency cache.
WARNING: /home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-daap_0.7.1.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc               | ETA:  0:07:25
WARNING: /home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-daap_0.7.1.bb: Error during finalise of /home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-daap_0.7.1.bb
ERROR: ExpansionError during parsing /home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-daap_0.7.1.bb
Traceback (most recent call last):
  File "/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1781, in Fetch.__init__(urls=['git://github.com/abdelgmartinezl/PythonDaap;protocol=https;branch=master', 'file://python-daap.patch', 'file://The-member-ob_type-is-not-present-in-the-pcapobject.patch'], d=<bb.data_smart.DataSmart object at 0x7f4aca421d30>, cache=True, localonly=False, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                         self.ud[url].unpack_tracer = unpack_tracer
  File "/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1339, in FetchData.__init__(url='git://github.com/abdelgmartinezl/PythonDaap;protocol=https;branch=master', d=<bb.data_smart.DataSmart object at 0x7f4aca421d30>, localonly=False):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)
  File "/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 254, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f4ac4d7b280>, d=<bb.data_smart.DataSmart object at 0x7f4aca421d30>):
    >        ud.setup_revisions(d)
  File "/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1374, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7f4aca421d30>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)
    File "/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1238, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f4ac4d7b280>, d=<bb.data_smart.DataSmart object at 0x7f4aca421d30>, name='default'):
         if srcrev == "INVALID" or not srcrev:
    >        raise FetchError("Please set a valid SRCREV for url %s (possible key names are %s, or use a ;rev=X URL parameter)" % (str(attempts), ud.url), ud.url)
         if srcrev == "AUTOINC":
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://github.com/abdelgmartinezl/PythonDaap;protocol=https;branch=master'. Please set a valid SRCREV for url ['SRCREV_default:pn-python3-daap', 'SRCREV_default', 'SRCREV:pn-python3-daap', 'SRCREV'] (possible key names are git://github.com/abdelgmartinezl/PythonDaap;protocol=https;branch=master, or use a ;rev=X URL parameter)
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]
ERROR: Parsing halted due to errors, see error messages above
Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/5fe27b31fd95b3dafc0721b324c42af08fda065e

**Comment by open-cobralibero** [comment]
**hi fairbird I still encounter the same error I downloaded everything again but it gives me an error**

ERROR: enigma2-plugin-extensions-epgimport-rytec-20230617-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1528"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/bin/python3-native:/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core/scripts:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/bin/allarch-oe-linux:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot/usr/bin/crossscripts:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/sbin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/usr/bin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/sbin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/recipe-sysroot-native/bin:/home/torres/Documenti/openpli-dreambox-oe-core/bitbake/bin:/home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/torres"; /usr/bin/env wget -t 2 -T 30 --passive-ftp -O /home/torres/Documenti/openpli-dreambox-oe-core/sources/rytec.sources.xml.20230617.gz.tmp -P /home/torres/Documenti/openpli-dreambox-oe-core/sources 'http://rytecepg.wanwizard.eu/rytec.sources.xml.20230617.gz' --progress=dot -v failed with exit code 8, no output
ERROR: enigma2-plugin-extensions-epgimport-rytec-20230617-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://rytecepg.wanwizard.eu/rytec.sources.xml.20230617.gz')
ERROR: Logfile of failure stored in: /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-epgimport-rytec/20230617/temp/log.do_fetch.615679
ERROR: Task (/home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-epgimport-rytec.bb:do_fetch) failed with exit code '1'

**Comment by fairbird** [comment]
Server down (Read Here)
https://forums.openpli.org/topic/96582-one-epg-server-is-down/#entry1579982

You can temporarily solve the problem manually (Rename rytec.sources.xml.20230617.gz.txt to rytec.sources.xml.20230617.gz.done and copy files to /sources dir.)

[rytec.sources.xml.20230617.gz](https://github.com/fairbird/openpli-dreambox-oe-core/files/13407746/rytec.sources.xml.20230617.gz)
[rytec.sources.xml.20230617.gz.txt](https://github.com/fairbird/openpli-dreambox-oe-core/files/13407747/rytec.sources.xml.20230617.gz.txt)

**Comment by open-cobralibero** [comment]
hi fairbird good morning thank you very much it seems that now it is going with the feile

**Comment by fairbird** [comment]
Server back to work again !!
