### ISSUE TITLE
Parsing halted due to errors

### ISSUE THREAD

**Issue by elhawaryn** [fairbird/openpli-dreambox-oe-core#75]
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
ERROR: ParseError at /home/elhawary/openpli-dreambox-oe-core/meta-dreambox/recipes-kodi/stb-kodi-dm820_21.bb:1: Could not include required file recipes-multimedia/kodi/stb-kodi_21.bb
ERROR: Parsing halted due to errors, see error messages above
WARNING: /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-mediacenter/kodi-addons/kodi-addon-inputstream-adaptive_git.bb: Error during finalise of /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-mediacenter/kodi-addons/kodi-addon-inputstream-adaptive_git.bb
WARNING: /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-mediacenter/kodi/stb-kodi_21.bb: Error during finalise of /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-mediacenter/kodi/stb-kodi_21.bb

**Comment by fairbird** [comment]
Already solved yesterday 
https://github.com/fairbird/openpli-dreambox-oe-core/commit/0588495851414789ef69c88c3173210c01fd7c98
