### ISSUE TITLE
new error since this morning

### ISSUE THREAD

**Issue by open-cobralibero** [fairbird/openpli-dreambox-oe-core#77]
**Hi friend, I've been having this error since this morning**

torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$ MACHINE=dm820 DISTRO=openpli make image  
[ -d /home/torres/Documenti/openpli-dreambox-oe-core/meta-images ] || make  update
make[1]: ingresso nella directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Updating Git repositories...
Già aggiornato.
Sincronizzazione URL sottomodulo per 'bitbake' in corso
Sincronizzazione URL sottomodulo per 'meta-openembedded' in corso
Sincronizzazione URL sottomodulo per 'meta-qt5.15' in corso
Sincronizzazione URL sottomodulo per 'openembedded-core' in corso
The openpli OE is now up-to-date.
make[1]: uscita dalla directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/env.source
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/local.conf
Building image for dm820
check internet connection: Online      
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
ERROR: The following layer directories do not exist:
ERROR:    /home/torres/Documenti/openpli-dreambox-oe-core/meta-images
ERROR: Please check BBLAYERS in /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
make: *** [Makefile:110: image] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
> /usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

You need to delete build directory or at least (tmp + conf) folder from inside it !!

**Comment by open-cobralibero** [comment]
> > /usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: l'uso o l'importazione degli ABC da 'collections' anziché da 'collections.abc' è deprecato a partire da Python 3.3 e nella 3.10 smetterà di funzionare
> 
> Devi eliminare la directory build o almeno la cartella (tmp + conf) dal suo interno !!

hi friend even if I delete it it gives me the same error

**Comment by fairbird** [comment]
That error not from core. It is from your builder tree ...

**Comment by open-cobralibero** [comment]
hi friend, I cloned the core again and it gives the same error even with the new core

**Comment by fairbird** [comment]
Why you are using (DISTRO) this command ?!!
> MACHINE=dm820 DISTRO=openpli make image

No need it just use 
> MACHINE=dm820 make image

Or use build script (build_image.sh) ...
Here no problem to compile DM820 or any boxes on Ubuntu 23.04 !!!

![Selection_001](https://github.com/fairbird/openpli-dreambox-oe-core/assets/1761779/7bd3b9e5-3037-4e2a-b892-57e19f8b63fc)

**Comment by open-cobralibero** [comment]
**hi friend, I cloned the core again and it gives the same error even with the new core**

orres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$ MACHINE=dm820 make image 
[ -d /home/torres/Documenti/openpli-dreambox-oe-core/meta-openembedded/meta-oe ] || make  update
make[1]: ingresso nella directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Updating Git repositories...
Già aggiornato.
Sincronizzazione URL sottomodulo per 'bitbake' in corso
Sincronizzazione URL sottomodulo per 'meta-openembedded' in corso
Sincronizzazione URL sottomodulo per 'meta-qt5.15' in corso
Sincronizzazione URL sottomodulo per 'openembedded-core' in corso
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core' in corso...
Percorso del sottomodulo 'bitbake': eseguito checkout di '4135a617ae16d509362b5bf56378139cdc0876d2'
Percorso del sottomodulo 'meta-openembedded': eseguito checkout di 'ec7ab6b435340bfc238add4bbe6fb3112494754e'
Percorso del sottomodulo 'meta-qt5.15': eseguito checkout di 'e710c451d210707bc6570357e7e123179cbb2d7e'
Percorso del sottomodulo 'openembedded-core': eseguito checkout di 'dfed7e63e199009ecca8e2e34f6a823c6e1677e0'
The openpli OE is now up-to-date.
make[1]: uscita dalla directory «/home/torres/Documenti/openpli-dreambox-oe-core»
[ -d /home/torres/Documenti/openpli-dreambox-oe-core/meta-images ] || make  update
make[1]: ingresso nella directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Updating Git repositories...
Già aggiornato.
Sincronizzazione URL sottomodulo per 'bitbake' in corso
Sincronizzazione URL sottomodulo per 'meta-openembedded' in corso
Sincronizzazione URL sottomodulo per 'meta-qt5.15' in corso
Sincronizzazione URL sottomodulo per 'openembedded-core' in corso
The openpli OE is now up-to-date.
make[1]: uscita dalla directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/env.source
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/local.conf
Building image for dm820
check internet connection: Online      
/usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
ERROR: The following layer directories do not exist:
ERROR:    /home/torres/Documenti/openpli-dreambox-oe-core/meta-images
ERROR: Please check BBLAYERS in /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
make: *** [Makefile:110: image] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
No need to clone source again and again ... the issue from your system ... maybe you update some packages and caused that problem
look here

> /usr/lib/python3/dist-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

system python problem ...
So that make this error in your build tree
> make[1]: ingresso nella directory «/home/torres/Documenti/openpli-dreambox-oe-core»
.
make[1]: uscita dalla directory «/home/torres/Documenti/openpli-dreambox-oe-core»
[ -d /home/torres/Documenti/openpli-dreambox-oe-core/meta-images ] || make update
make[1]: ingresso nella directory «/home/torres/Documenti/openpli-dreambox-oe-core»

**Comment by audi06** [comment]
Delete the "meta-images" line in the Makefile and try again.

https://github.com/fairbird/openpli-dreambox-oe-core/commit/73bd9a77a5046ddeec89f633cba45c5825ee78dc#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R58

```
diff --git a/Makefile b/Makefile
index 43e33272..900078ad 100644
--- a/Makefile
+++ b/Makefile
@@ -54,8 +54,7 @@ BBLAYERS ?= \
        $(CURDIR)/openembedded-core/meta \
        $(CURDIR)/meta-openpli \
        $(CURDIR)/meta-dreambox \
-       $(CURDIR)/meta-qt5.15 \
-       $(CURDIR)/meta-images
+       $(CURDIR)/meta-qt5.15
 
 CONFFILES = \
        $(TOPDIR)/env.source \
```

**Comment by fairbird** [comment]
OH ... That is my mistake ... meta-images it is my privet test meta ...
Sorry .. 
https://github.com/fairbird/openpli-dreambox-oe-core/commit/16a5bd7353b11f54b7e3efa62e3a07456b16039a

**Comment by fairbird** [comment]
@audi06
Do you have dreamone or two ?!! If yes please give help here !!
https://github.com/fairbird/openpli-dreambox-oe-core/issues/74#issuecomment-1872977436
