### ISSUE TITLE
error

### ISSUE THREAD

**Issue by open-cobralibero** [fairbird/openpli-dreambox-oe-core#78]
**Good morning my friend this **error****

torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$ MACHINE=dm820 make image
[ -d /home/torres/Documenti/openpli-dreambox-oe-core/meta-openembedded/meta-oe ] || make  update
make[1]: ingresso nella directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Updating Git repositories...
Già aggiornato.
Sottomodulo 'bitbake' (git://git.openembedded.org/bitbake) registrato per il percorso 'bitbake'
Sottomodulo 'meta-openembedded' (git://git.openembedded.org/meta-openembedded) registrato per il percorso 'meta-openembedded'
Sottomodulo 'meta-qt5.15' (https://github.com/oe-mirrors/meta-qt5.15.git) registrato per il percorso 'meta-qt5.15'
Sottomodulo 'openembedded-core' (git://git.openembedded.org/openembedded-core) registrato per il percorso 'openembedded-core'
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/bitbake' in corso...
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/meta-openembedded' in corso...
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/meta-qt5.15' in corso...
Clone in '/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core' in corso...
Percorso del sottomodulo 'bitbake': eseguito checkout di 'de8ba2770d9a1a94af3d084f9540da7e2fae6022'
Percorso del sottomodulo 'meta-openembedded': eseguito checkout di '7d8115d5507bac6c018fbff8a7aa9bc513c2bc46'
Percorso del sottomodulo 'meta-qt5.15': eseguito checkout di 'e710c451d210707bc6570357e7e123179cbb2d7e'
Percorso del sottomodulo 'openembedded-core': eseguito checkout di '0e8a4142bb90a92d175df6b2537d24a372356f98'
The openpli OE is now up-to-date.
make[1]: uscita dalla directory «/home/torres/Documenti/openpli-dreambox-oe-core»
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/env.source
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/torres/Documenti/openpli-dreambox-oe-core/build/conf/local.conf
Building image for dm820
check internet connection: Online      
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |                                           | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:00:43
Parsing of 3551 .bb files complete (0 cached, 3551 parsed). 5372 targets, 682 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync
ERROR: Nothing RPROVIDES 'shellinabox' (but /home/torres/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'shellinabox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['shellinabox']
ERROR: Required build target 'openpli-enigma2-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-image', 'shellinabox']

Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/cb12c53a8722ad88a07294f27bfa95785ec61978

**Comment by open-cobralibero** [comment]
error: cargo failed with code: 101
| 
| 
| ERROR Backend subprocess exited when trying to invoke build_wheel
| WARNING: /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.557732:189 exit 1 from 'nativepython3 -m build --no-isolation --wheel --outdir /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/dist /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/bcrypt-4.1.1'
| WARNING: Backtrace (BB generated script):
| 	#1: python_pep517_do_compile, /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.557732, line 189
| 	#2: do_compile, /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.557732, line 165
| 	#3: main, /home/torres/Documenti/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.557732, line 200
ERROR: Task (/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-bcrypt_4.1.1.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9143 tasks of which 9071 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-bcrypt_4.1.1.bb:do_compile
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:109: image] Errore 1
torres@torres-Nitro-AN517-54:~/Documenti/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
You have wrong compiled for () So remove tmp folder or clean package first then compile image again
> ERROR: Task (/home/torres/Documenti/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-bcrypt_4.1.1.bb:do_compile) failed with exit code '1'

If you need to clean package

> cd build
source env.source; MACHINE=dm820 bitbake -c cleanall -f python3-bcrypt 
cd ..

**Comment by open-cobralibero** [comment]
**Hi friend it still gives me this error even when I delete the build and clone the core and with this command MACHINE=dm820 make image**

ERROR Backend subprocess exited when trying to invoke build_wheel
| WARNING: /home/torres/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.1849079:189 exit 1 from 'nativepython3 -m build --no-isolation --wheel --outdir /home/torres/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/dist /home/torres/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/bcrypt-4.1.1'
| WARNING: Backtrace (BB generated script):
| 	#1: python_pep517_do_compile, /home/torres/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.1849079, line 189
| 	#2: do_compile, /home/torres/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.1849079, line 165
| 	#3: main, /home/torres/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-bcrypt/4.1.1/temp/run.do_compile.1849079, line 200
ERROR: Task (/home/torres/Musica/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-bcrypt_4.1.1.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9143 tasks of which 6 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/torres/Musica/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-bcrypt_4.1.1.bb:do_compile
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:109: image] Errore 1
torres@torres-Nitro-AN517-54:~/Musica/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Update core then try to build image again after this commit ...
https://github.com/fairbird/openpli-dreambox-oe-core/commit/64e440b0d66ba794010118e7f1aec50f112bab1e

**Comment by open-cobralibero** [comment]
Hi friend thanks for filling in now

**Comment by fairbird** [comment]
If Solved .. Please close the issue !!
Thank you for feedback !!
