### ISSUE TITLE
Plugins-BacupSuite

### ISSUE THREAD

**Issue by enry74** [fairbird/openpli-dreambox-oe-core#8]
Good evening friend that is a question to ask you but the plugins-BackupSuite I can't find it is not implemented?

Thank you

**Comment by fairbird** [comment]
Add it...
https://github.com/fairbird/openpli-dreambox-oe-core/commit/f9eed3875c558d8e345e7ce3f8f28f0c4258e6e4

**Comment by enry74** [comment]
Thank you

**Comment by fairbird** [comment]
:+1:

**Comment by enry74** [comment]
Good evening friend I compiled image for dm 800se with oe-core downloaded yesterday but the backupsuite does not fit in the plugins maybe there is some error somewhere.

Thank you

**Comment by fairbird** [comment]
I can not help you with this issue ... backupsuite plugin not from this source so no support here ..
You can ask (persianpros) in his source
https://github.com/persianpros/BackupSuite-PLi
