### ISSUE TITLE
openpli-enigma2-feed', 'sabnzbd

### ISSUE THREAD

**Issue by elhawaryn** [fairbird/openpli-dreambox-oe-core#80]
Building feed for dm820
check internet connection: Online      
Loading cache: 100% |                                           | ETA:  --:--:--
Loaded 0 entries from dependency cache.
NOTE: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-qt5.15/recipes-qt/packagegroups/nativesdk-packagegroup-qt5-toolchain-host.bb: QA Issue: nativesdk-packagegroup-qt5-toolchain-host: native/nativesdk class is not inherited last, this can result in unexpected behaviour. Classes inherited after native/nativesdk: allarch.bbclass [native-last]
Parsing recipes: 100% |##########################################| Time: 0:02:16
Parsing of 3544 .bb files complete (0 cached, 3544 parsed). 5359 targets, 682 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'sabnzbd' (but /home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb DEPENDS on or otherwise requires it). Close matches:
  sabnzbd3
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'sabnzbd']

Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/Desktop/2/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Do not build image or feed until I finish to update core ...
I'm moving to python 3.12.1 and need some times !!

**Comment by fairbird** [comment]
Issue solved !!
But do not build new image .. Core and e2 still need some updates !!
