### ISSUE TITLE
ERROR: python3-yt-dlp-git

### ISSUE THREAD

**Issue by elhawaryn** [fairbird/openpli-dreambox-oe-core#81]
ERROR: python3-yt-dlp-git-r0 do_compile: 'python3 setup.py bdist_wheel ' execution failed.
ERROR: python3-yt-dlp-git-r0 do_compile: ExecutionError('/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/temp/run.do_compile.4061327', 1, None, None)
ERROR: Logfile of failure stored in: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/temp/log.do_compile.4061327
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 PYTHON=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/recipe-sysroot-native/usr/bin/python3-native/python3 lazy-extractors yt-dlp completion-bash
| /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/recipe-sysroot-native/usr/bin/python3-native/python3 devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py
| mkdir -p zip
| mkdir -p completions/bash
| for d in yt_dlp yt_dlp/dependencies yt_dlp/postprocessor yt_dlp/networking yt_dlp/extractor yt_dlp/downloader yt_dlp/compat yt_dlp/compat/urllib yt_dlp/utils ; do \
|   mkdir -p zip/$d ;\
|   cp -pPR $d/*.py zip/$d/ ;\
| done
| /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/recipe-sysroot-native/usr/bin/python3-native/python3 devscripts/bash-completion.py
| cd zip ; touch -t 200001010101 yt_dlp/*.py yt_dlp/*/*.py yt_dlp/*/*/*.py
| mv zip/yt_dlp/__main__.py zip/
| cd zip ; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py yt_dlp/*/*/*.py __main__.py
| rm -rf zip
| echo '#!/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/recipe-sysroot-native/usr/bin/python3-native/python3' > yt-dlp
| cat yt-dlp.zip >> yt-dlp
| rm yt-dlp.zip
| chmod a+x yt-dlp
| /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/recipe-sysroot-native/usr/bin/python3-native/python3: can't open file '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-yt-dlp/git/git/setup.py': [Errno 2] No such file or directory
| ERROR: 'python3 setup.py bdist_wheel ' execution failed.
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-yt-dlp.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 10588 tasks of which 10127 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/python3-yt-dlp.bb:do_compile
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by fairbird** [comment]
Already updated Yesterday ! But also I will update all core to latest update today !
https://github.com/fairbird/openpli-dreambox-oe-core/commit/21282f06b5e5f077fef27a096d28c1c622d1b603
