### ISSUE TITLE
Error 89 Fatal: Failed to run dreambox-secondstage.postinst

### ISSUE THREAD

**Issue by elhawaryn** [fairbird/openpli-dreambox-oe-core#82]
[*] Remounting '/dev/mmcblk0p2' to '/data'
[*] Creating ext4 filesystem 'dreambox-rootfs' on /dev/mmcblk0p1
mke2fs 1.43-WIP (18-May-2015)
Creating filesystem with 243712 4k blocks and 60928 inodes
Filesystem UUID: fef3f783-2583-473c-abf8-b9e3d8d6ffc7
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376

Allocating group tables: 0/8   done                            
Writing inode tables: 0/8   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/8   done

[*] Mounting '/dev/mmcblk0p1' to '/mnt'
[*] Extracting '/tmp/Sal9sd' to '/mnt'
[*] Mounting '/dev' to '/mnt/dev'
[*] Mounting '/proc' to '/mnt/proc'
[*] Mounting '/run' to '/mnt/run'
[*] Mounting '/sys' to '/mnt/sys'
[*] Mounting '/tmp' to '/mnt/tmp'
/bin/sh: error while loading shared libraries: libtinfo.so.5: cannot stat shared object: Error 89
Fatal: Failed to run dreambox-secondstage.postinst
[*] Unmounting '/mnt/tmp'
[*] Unmounting '/mnt/sys'
[*] Unmounting '/mnt/run'
[*] Unmounting '/mnt/proc'
[*] Unmounting '/mnt/dev'
[*] Unmounting '/mnt'

**Comment by fairbird** [comment]
There is some thing happens wit your build (missing libtinfo) !!
You need to remove tmp folder and build new mages !
