### ISSUE TITLE
ERROR: davfs2-1.7.0-r0 do_configure: configure failed

### ISSUE THREAD

**Issue by elhawaryn** [fairbird/openpli-dreambox-oe-core#83]
ERROR: inadyn-mt-v.02.24.44-r3 do_fetch: Fetcher failure for URL: 'https://sourceforge.net/projects/inadyn-mt/files/inadyn-mt/inadyn-mt.v.02.24.44/inadyn-mt.v.02.24.44.tar.gz'. Checksum mismatch!
File: '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/sources/inadyn-mt.v.02.24.44.tar.gz.tmp' has md5 checksum '09ab67a06fa63df37196061f7a25820a' when '0652d99aab1249d6a3afe4d65861e77b' was expected
File: '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/sources/inadyn-mt.v.02.24.44.tar.gz.tmp' has sha256 checksum '24e6cdc797117eba93f288ba67dafaed6f953f5b7c1de3f7cc9151c2c8019c44' when 'f894b5ab92ed4ec4cae2eccc99efef1aa18c0f5f02de66025e50833cc9063c3c' was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[sha256sum] = "24e6cdc797117eba93f288ba67dafaed6f953f5b7c1de3f7cc9151c2c8019c44"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.
ERROR: inadyn-mt-v.02.24.44-r3 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://sourceforge.net/projects/inadyn-mt/files/inadyn-mt/inadyn-mt.v.02.24.44/inadyn-mt.v.02.24.44.tar.gz')
ERROR: Logfile of failure stored in: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/inadyn-mt/v.02.24.44/temp/log.do_fetch.66457
ERROR: Task (/home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-connectivity/inadyn-mt/inadyn-mt.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 13964 tasks of which 2444 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-connectivity/inadyn-mt/inadyn-mt.bb:do_fetch
Summary: There were 4 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/Desktop/2/openpli-dreambox-oe-core$ MACHINE=dm820 make feed
Building feed for dm820
check internet connection: Online      
Loading cache: 100% |############################################| Time: 0:00:03
Loaded 5085 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:00:46
Parsing of 3571 .bb files complete (3254 cached, 317 parsed). 5404 targets, 681 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync

Build Configuration:
BB_VERSION           = "2.7.2"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-23.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "GCC-13.2"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:a6c4624a684f7d5a2dbd21acbe74ecf611f4f839"
meta                 = "HEAD:311d2606a70528e14093dd93178a2c7170718333"
meta-openpli         
meta-dreambox        = "develop:b99c900bcefe26d114e2635077b2799c1b701ae7"
meta-qt5.15          = "HEAD:c5f4bcaf1caf731e06470e26f561eec90d75cbd4"

Sstate summary: Wanted 2881 Local 1188 Mirrors 0 Missed 1693 Current 5754 (41% match, 80% complete)
Removing 25 stale sstate objects for arch dm820: 100% |##########| Time: 0:00:00
NOTE: Executing Tasks
ERROR: davfs2-1.7.0-r0 do_configure: configure failed
ERROR: davfs2-1.7.0-r0 do_configure: ExecutionError('/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/temp/run.do_configure.118103', 1, None, None)
ERROR: Logfile of failure stored in: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/temp/log.do_configure.118103
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openembedded/meta-oe/recipes-support/neon/neon_0.33.0.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/base-files/base-files_3.0.14.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/base-passwd/base-passwd_3.6.3.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/glibc/glibc_2.39.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_13.2.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_13.2.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/libtool/libtool-cross_2.4.7.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/libtool/libtool-native_2.4.7.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-extended/shadow/shadow-sysroot_4.6.bb:do_populate_sysroot', '/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-extended/shadow/shadow_4.14.2.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-core/gettext/gettext_0.22.4.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/autoconf/autoconf_2.72e.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/automake/automake_1.16.5.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/recipes-extended/shadow/shadow_4.14.2.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['neon', 'openssl', 'base-files', 'base-passwd', 'expat', 'gettext-minimal-native', 'glib-2.0', 'glibc', 'libxcrypt', 'ncurses', 'readline', 'util-linux-libuuid', 'util-linux', 'zlib', 'binutils-cross-mipsel', 'gcc-cross-mipsel', 'gcc-runtime', 'libgcc', 'libtool-cross', 'libtool-native', 'm4-native', 'opkg-utils', 'python3', 'quilt-native', 'vala', 'bzip2', 'cracklib', 'libnsl2', 'libtirpc', 'libpam', 'shadow-sysroot', 'shadow', 'texinfo-dummy-native', 'xz', 'gobject-introspection', 'linux-libc-headers', 'bash-completion', 'gdbm', 'libcap-ng', 'libffi', 'libpcre2', 'libproxy', 'sqlite3', 'gettext-native', 'zlib-native', 'autoconf-native', 'automake-native', 'flex-native', 'gnu-config-native', 'patch-native', 'pkgconfig-native', 'pseudo-native', 'shadow-native', 'xz-native', 'zstd-native', 'attr-native', 'gmp-native', 'libbsd-native', 'libmd-native', 'libmpc-native', 'mpfr-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing shell function do_configure
| automake (GNU automake) 1.16.5
| Copyright (C) 2021 Free Software Foundation, Inc.
| License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
| This is free software: you are free to change and redistribute it.
| There is NO WARRANTY, to the extent permitted by law.
| 
| Written by Tom Tromey <tromey@redhat.com>
|        and Alexandre Duret-Lutz <adl@gnu.org>.
| AUTOV is 1.16
| NOTE: Executing ACLOCAL="aclocal --system-acdir=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot/usr/share/aclocal/ --automake-acdir=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/share/aclocal-1.16" autoreconf -Wcross --verbose --install --force --exclude=autopoint -I /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/davfs2-1.7.0/config/ -I /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/share/aclocal/
| autoreconf: export WARNINGS=cross,no-obsolete
| autoreconf: Entering directory '.'
| autoreconf: running: aclocal --system-acdir=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot/usr/share/aclocal/ --automake-acdir=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/share/aclocal-1.16 -I /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/davfs2-1.7.0/config/ -I /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/share/aclocal/ --force -I config
| autoreconf: configure.ac: tracing
| autoreconf: configure.ac: not using Libtool
| autoreconf: configure.ac: not using Intltool
| autoreconf: configure.ac: not using Gtkdoc
| autoreconf: running: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/bin/autoconf --include=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/davfs2-1.7.0/config/ --include=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/share/aclocal/ --force
| autoreconf: running: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/bin/autoheader --include=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/davfs2-1.7.0/config/ --include=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/share/aclocal/ --force
| autoreconf: running: automake --add-missing --copy --force-missing
| man/Makefile.am:53: warning: '%'-style pattern rules are a GNU make extension
| man/de/Makefile.am:52: warning: '%'-style pattern rules are a GNU make extension
| man/es/Makefile.am:53: warning: '%'-style pattern rules are a GNU make extension
| autoreconf: 'config/install-sh' is updated
| autoreconf: 'config/config.sub' is updated
| autoreconf: 'config/config.guess' is updated
| autoreconf: Leaving directory '.'
| NOTE: Running ../davfs2-1.7.0/configure  --build=x86_64-linux 		  --host=mipsel-oe-linux 		  --target=mipsel-oe-linux 		  --prefix=/usr 		  --exec_prefix=/usr 		  --bindir=/usr/bin 	  --sbindir=/usr/sbin 		  --libexecdir=/usr/libexec 		  --datadir=/usr/share 		  --sysconfdir=/etc 		  --sharedstatedir=/com   --localstatedir=/var 		  --libdir=/usr/lib 		  --includedir=/usr/include 		  --oldincludedir=/usr/include 		  --infodir=/usr/share/info 		  --mandir=/usr/share/man 		  --disable-silent-rules 		  --disable-dependency-tracking 		  --with-libtool-sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot --with-neon                 ac_cv_path_NEON_CONFIG=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/neon-config
| configure: WARNING: unrecognized options: --with-libtool-sysroot
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/site/endian-little
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/site/mips-common
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/site/common-linux
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/site/common-glibc
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/site/mipsel-linux
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/openembedded-core/meta/site/common
| configure: loading site script /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot/usr/share/mipsel-oe-linux_config_site.d/ncurses_config
| checking for a BSD-compatible install... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/hosttools/install -c
| checking whether build environment is sane... yes
| checking for mipsel-oe-linux-strip... mipsel-oe-linux-strip
| checking for a race-free mkdir -p... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/hosttools/mkdir -p
| checking for gawk... gawk
| checking whether make sets $(MAKE)... yes
| checking whether make supports nested variables... yes
| checking for mipsel-oe-linux-gcc... mipsel-oe-linux-gcc  -mel -mabi=32 -mhard-float -march=mips32 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot
| checking whether the C compiler works... yes
| checking for C compiler default output file name... a.out
| checking for suffix of executables...
| checking whether we are cross compiling... yes
| checking for suffix of object files... o
| checking whether the compiler supports GNU C... yes
| checking whether mipsel-oe-linux-gcc  -mel -mabi=32 -mhard-float -march=mips32 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot accepts -g... yes
| checking for mipsel-oe-linux-gcc  -mel -mabi=32 -mhard-float -march=mips32 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot option to enable C11 features... none needed
| checking whether mipsel-oe-linux-gcc  -mel -mabi=32 -mhard-float -march=mips32 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot understands -c and -o together... yes
| checking whether make supports the include directive... yes (GNU style)
| checking dependency style of mipsel-oe-linux-gcc  -mel -mabi=32 -mhard-float -march=mips32 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot... none
| checking whether ln -s works... yes
| checking for a sed that does not truncate output... (cached) sed
| checking whether NLS is requested... yes
| checking for msgfmt... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/bin/msgfmt
| checking for gmsgfmt... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/bin/msgfmt
| checking for xgettext... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/bin/xgettext
| checking for msgmerge... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot-native/usr/bin/msgmerge
| checking build system type... x86_64-pc-linux-gnu
| checking host system type... mipsel-oe-linux-gnu
| checking for ld... mipsel-oe-linux-ld --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot
| checking if the linker (mipsel-oe-linux-ld --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot  ) is GNU ld... yes
| checking for shared library run path origin... done
| checking 32-bit host C ABI... yes
| checking how to run the C preprocessor... mipsel-oe-linux-gcc -E --sysroot=/home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/recipe-sysroot  -mel -mabi=32 -mhard-float -march=mips32 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64
| checking for egrep -e... /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/hosttools/grep -E
| checking for ELF binary format... yes
| checking for the common suffixes of directories in the library search path... lib,lib32,lib
| checking for CFPreferencesCopyAppValue... no
| checking for CFLocaleCopyCurrent... no
| checking for GNU gettext in libc... yes
| checking whether to use NLS... yes
| checking where the gettext function comes from... libc
| checking for neon-config... (cached) /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/neon-config
| configure: ignoring non-executable /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/neon-config
| configure: error: could not find neon
| NOTE: The following config.log files may provide further information.
| NOTE: /home/elhawary/Desktop/2/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/davfs2/1.7.0/build/config.log
| ERROR: configure failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-filesystems/davfs2/davfs2_1.7.0.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 12761 tasks of which 12493 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/Desktop/2/openpli-dreambox-oe-core/meta-openpli/recipes-filesystems/davfs2/davfs2_1.7.0.bb:do_configure
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by fairbird** [comment]
I know about this error ... I will solve it later !

**Comment by fairbird** [comment]
Solved !! 
Have you try again please ?!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/6737b8a422342d8a682f526c75d48f79ff2567e6
