### ISSUE TITLE
python3-cryptography_42.0.2.bb:do_compile) failed with exit code '1'

### ISSUE THREAD

**Issue by atefganm** [fairbird/openpli-dreambox-oe-core#85]
Removing 6 stale sstate objects for arch dm820: 100% |#########################################################################################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
ERROR: python3-cryptography-42.0.2-r0 do_compile: ExecutionError('/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/temp/run.do_compile.1543812', 1, None, None)
ERROR: Logfile of failure stored in: /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/temp/log.do_compile.1543812
Log data follows:
| DEBUG: Executing shell function do_compile
| * Getting build dependencies for wheel...
| WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
| running egg_info
| writing src/cryptography.egg-info/PKG-INFO
| writing dependency_links to src/cryptography.egg-info/dependency_links.txt
| writing requirements to src/cryptography.egg-info/requires.txt
| writing top-level names to src/cryptography.egg-info/top_level.txt
| reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
| reading manifest template 'MANIFEST.in'
| warning: no files found matching '*.c' under directory 'src/_cffi_src'
| warning: no files found matching '*.h' under directory 'src/_cffi_src'
| no previously-included directories found matching 'docs/_build'
| warning: no previously-included files found matching 'vectors'
| warning: no previously-included files matching '*' found under directory 'vectors'
| warning: no previously-included files found matching 'src/rust/target'
| warning: no previously-included files matching '*' found under directory 'src/rust/target'
| warning: no previously-included files matching '*' found under directory '.github'
| warning: no previously-included files found matching 'release.py'
| warning: no previously-included files found matching '.readthedocs.yml'
| warning: no previously-included files found matching 'ci-constraints-requirements.txt'
| warning: no previously-included files found matching 'mypy.ini'
| adding license file 'LICENSE'
| adding license file 'LICENSE.APACHE'
| adding license file 'LICENSE.BSD'
| writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
| * Building wheel...
| WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
| running bdist_wheel
| running build
| running build_py
| running egg_info
| writing src/cryptography.egg-info/PKG-INFO
| writing dependency_links to src/cryptography.egg-info/dependency_links.txt
| writing requirements to src/cryptography.egg-info/requires.txt
| writing top-level names to src/cryptography.egg-info/top_level.txt
| reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
| reading manifest template 'MANIFEST.in'
| warning: no files found matching '*.c' under directory 'src/_cffi_src'
| warning: no files found matching '*.h' under directory 'src/_cffi_src'
| no previously-included directories found matching 'docs/_build'
| warning: no previously-included files found matching 'vectors'
| warning: no previously-included files matching '*' found under directory 'vectors'
| warning: no previously-included files found matching 'src/rust/target'
| warning: no previously-included files matching '*' found under directory 'src/rust/target'
| warning: no previously-included files matching '*' found under directory '.github'
| warning: no previously-included files found matching 'release.py'
| warning: no previously-included files found matching '.readthedocs.yml'
| warning: no previously-included files found matching 'ci-constraints-requirements.txt'
| warning: no previously-included files found matching 'mypy.ini'
| adding license file 'LICENSE'
| adding license file 'LICENSE.APACHE'
| adding license file 'LICENSE.BSD'
| writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
| running build_ext
| running build_rust
| cargo rustc --lib --message-format=json-render-diagnostics --manifest-path src/rust/Cargo.toml --target mipsel-oe-linux-gnu --release -v --features pyo3/extension-module --crate-type cdylib --
|        Fresh unicode-ident v1.0.12
|        Fresh pkg-config v0.3.29
|        Fresh vcpkg v0.2.15
|        Fresh autocfg v1.1.0
|        Fresh cfg-if v1.0.0
|        Fresh proc-macro2 v1.0.78
|        Fresh cc v1.0.83
|        Fresh target-lexicon v0.12.13
|        Fresh libc v0.2.152
|        Fresh quote v1.0.35
|        Fresh smallvec v1.13.1
|        Fresh heck v0.4.1
|        Fresh foreign-types-shared v0.1.1
|        Fresh scopeguard v1.2.0
|        Fresh once_cell v1.19.0
|        Fresh syn v2.0.48
|        Fresh lock_api v0.4.11
|        Fresh parking_lot_core v0.9.9
|        Fresh foreign-types v0.3.2
|        Fresh bitflags v2.4.2
|        Fresh pyo3-build-config v0.20.2
|        Fresh asn1_derive v0.15.5
|        Fresh openssl-sys v0.9.99
|        Fresh openssl-macros v0.1.1
|        Fresh pyo3-macros-backend v0.20.2
|        Fresh memoffset v0.9.0
|        Fresh parking_lot v0.12.1
|        Fresh asn1 v0.15.5
|        Fresh openssl v0.10.63
|        Fresh pyo3-macros v0.20.2
|        Fresh cryptography-x509 v0.1.0 (/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cryptography-42.0.2/src/rust/cryptography-x509)
|        Fresh indoc v2.0.4
|        Fresh unindent v0.2.3
| warning: /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/build/cryptography-cffi-7234251a8580ef35/out/_openssl.c: In function 'Cryptography_DTLSv1_get_timeout':
| warning: /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/build/cryptography-cffi-7234251a8580ef35/out/_openssl.c:1044:25: warning: conversion from '__suseconds64_t' {aka 'long long int'} to 'long int' may change value [-Wconversion]
| warning:  1044 |             *ptv_usec = tv.tv_usec;
| warning:       |                         ^~
|        Fresh pyo3-ffi v0.20.2
|        Fresh base64 v0.21.7
|        Fresh cryptography-x509-verification v0.1.0 (/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cryptography-42.0.2/src/rust/cryptography-x509-verification)
|        Fresh cryptography-openssl v0.1.0 (/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cryptography-42.0.2/src/rust/cryptography-openssl)
|        Fresh cryptography-key-parsing v0.1.0 (/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cryptography-42.0.2/src/rust/cryptography-key-parsing)
|        Fresh self_cell v1.0.3
|    Compiling pyo3 v0.20.2
|        Fresh pem v3.0.3
|     Building [========================>  ] 74/77: pyo3
|      Running `rustc --crate-name pyo3 --edition=2021 /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cargo_home/bitbake/pyo3-0.20.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no '--warn=clippy::useless_transmute' '--warn=clippy::used_underscore_binding' --warn=unused_lifetimes '--warn=clippy::unnecessary_wraps' '--warn=clippy::todo' --warn=rust_2021_prelude_collisions --warn=rust_2018_idioms '--warn=clippy::manual_ok_or' '--warn=clippy::manual_assert' '--warn=clippy::let_unit_value' --warn=invalid_doc_attributes '--warn=clippy::flat_map_option' '--warn=clippy::filter_map_next' '--warn=clippy::explicit_iter_loop' '--warn=clippy::explicit_into_iter_loop' --warn=elided_lifetimes_in_paths '--warn=clippy::dbg_macro' '--warn=clippy::checked_conversions' '--warn=rustdoc::broken_intra_doc_links' '--warn=rustdoc::bare_urls' -C overflow-checks=on --cfg 'feature="abi3"' --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="indoc"' --cfg 'feature="macros"' --cfg 'feature="pyo3-macros"' --cfg 'feature="unindent"' -C metadata=46e34c4e4d5f8b19 -C extra-filename=-46e34c4e4d5f8b19 --out-dir /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps --target mipsel-oe-linux-gnu -C linker=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/wrapper/target-rust-ccld -L dependency=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps -L dependency=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/release/deps --extern cfg_if=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libcfg_if-defcad5d82fc3031.rmeta --extern indoc=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/release/deps/libindoc-96e10ef8fd69bfb7.so --extern libc=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/liblibc-38df49dd67b16444.rmeta --extern memoffset=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libmemoffset-a318f9742636d7ad.rmeta --extern parking_lot=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libparking_lot-04b144b60930d4b6.rmeta --extern pyo3_ffi=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libpyo3_ffi-fd542f569bb7c8ba.rmeta --extern pyo3_macros=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/release/deps/libpyo3_macros-f99ad9464d8cd6cc.so --extern unindent=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libunindent-442ef0260f01639a.rmeta --cap-lints allow -L /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/recipe-sysroot/usr/lib/rustlib/mipsel-oe-linux-gnu/lib --remap-path-prefix=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2=/usr/src/debug/python3-cryptography/42.0.2 --cfg Py_3_6 --cfg Py_3_7 --cfg Py_3_8 --cfg Py_3_9 --cfg Py_3_10 --cfg Py_3_11 --cfg Py_3_12 --cfg 'py_sys_config="WITH_THREAD"' --cfg thread_local_const_init --cfg invalid_from_utf8_lint`
| error[E0432]: unresolved import `std::sync::atomic::AtomicI64`
|  --> /usr/src/debug/python3-cryptography/42.0.2/cargo_home/bitbake/pyo3-0.20.2/src/impl_/pymodule.rs:6:25
|   |
| 6 | use std::sync::atomic::{AtomicI64, Ordering};
|   |                         ^^^^^^^^^
|   |                         |
|   |                         no `AtomicI64` in `sync::atomic`
|   |                         help: a similar name exists in the module: `AtomicI32`
| 
| For more information about this error, try `rustc --explain E0432`.
| error: could not compile `pyo3` (lib) due to previous error
| 
| Caused by:
|   process didn't exit successfully: `rustc --crate-name pyo3 --edition=2021 /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cargo_home/bitbake/pyo3-0.20.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no '--warn=clippy::useless_transmute' '--warn=clippy::used_underscore_binding' --warn=unused_lifetimes '--warn=clippy::unnecessary_wraps' '--warn=clippy::todo' --warn=rust_2021_prelude_collisions --warn=rust_2018_idioms '--warn=clippy::manual_ok_or' '--warn=clippy::manual_assert' '--warn=clippy::let_unit_value' --warn=invalid_doc_attributes '--warn=clippy::flat_map_option' '--warn=clippy::filter_map_next' '--warn=clippy::explicit_iter_loop' '--warn=clippy::explicit_into_iter_loop' --warn=elided_lifetimes_in_paths '--warn=clippy::dbg_macro' '--warn=clippy::checked_conversions' '--warn=rustdoc::broken_intra_doc_links' '--warn=rustdoc::bare_urls' -C overflow-checks=on --cfg 'feature="abi3"' --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="indoc"' --cfg 'feature="macros"' --cfg 'feature="pyo3-macros"' --cfg 'feature="unindent"' -C metadata=46e34c4e4d5f8b19 -C extra-filename=-46e34c4e4d5f8b19 --out-dir /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps --target mipsel-oe-linux-gnu -C linker=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/wrapper/target-rust-ccld -L dependency=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps -L dependency=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/release/deps --extern cfg_if=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libcfg_if-defcad5d82fc3031.rmeta --extern indoc=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/release/deps/libindoc-96e10ef8fd69bfb7.so --extern libc=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/liblibc-38df49dd67b16444.rmeta --extern memoffset=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libmemoffset-a318f9742636d7ad.rmeta --extern parking_lot=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libparking_lot-04b144b60930d4b6.rmeta --extern pyo3_ffi=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libpyo3_ffi-fd542f569bb7c8ba.rmeta --extern pyo3_macros=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/release/deps/libpyo3_macros-f99ad9464d8cd6cc.so --extern unindent=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/build/target/mipsel-oe-linux-gnu/release/deps/libunindent-442ef0260f01639a.rmeta --cap-lints allow -L /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/recipe-sysroot/usr/lib/rustlib/mipsel-oe-linux-gnu/lib --remap-path-prefix=/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2=/usr/src/debug/python3-cryptography/42.0.2 --cfg Py_3_6 --cfg Py_3_7 --cfg Py_3_8 --cfg Py_3_9 --cfg Py_3_10 --cfg Py_3_11 --cfg Py_3_12 --cfg 'py_sys_config="WITH_THREAD"' --cfg thread_local_const_init --cfg invalid_from_utf8_lint` (exit status: 1)
| error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path src/rust/Cargo.toml --target mipsel-oe-linux-gnu --release -v --features pyo3/extension-module --crate-type cdylib --` failed with code 101
| 
| ERROR Backend subprocess exited when trying to invoke build_wheel
| WARNING: /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/temp/run.do_compile.1543812:190 exit 1 from 'nativepython3 -m build --no-isolation --wheel --outdir /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/dist /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/cryptography-42.0.2'
| WARNING: Backtrace (BB generated script):
| 	#1: python_pep517_do_compile, /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/temp/run.do_compile.1543812, line 190
| 	#2: do_compile, /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/temp/run.do_compile.1543812, line 166
| 	#3: main, /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/python3-cryptography/42.0.2/temp/run.do_compile.1543812, line 201
ERROR: Task (/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-cryptography_42.0.2.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 8818 tasks of which 8808 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/openembedded-core/meta/recipes-devtools/python/python3-cryptography_42.0.2.bb:do_compile
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:109: image] Error 1
atef@atef-ganm:~/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
This already solved !! Do you clean your tmp folder ?!!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/452a5272954df6257595b0aac0ccf0eecc4b050a

**Comment by atefganm** [comment]
The core was cloned yesterday and this commitment is old

**Comment by fairbird** [comment]
Update core and try again !!
