### ISSUE TITLE
error enigma2

### ISSUE THREAD

**Issue by enry74** [fairbird/openpli-dreambox-oe-core#9]
hi friend this ERROR: Task (/home/elcobra/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_compile) failed with exit code '1'
since you changed the core.

Thank you!

**Comment by fairbird** [comment]
Don't send error like this .... Totally useless...
You should upload full error logo ...
I cannot do anything with that line.

AnyWay Fixed
https://github.com/fairbird/enigma2-dreambox/commit/57a576cb2c14ceb95f3a5c62f5e0cd87d7f0e16e
