### ISSUE TITLE
unable to build image

### ISSUE THREAD

**Issue by karikash11** [fairbird/openpli-dreambox-oe-core#90]
Hello.
I am unable to compile image.
With ubuntu 23.10  "sudo dpkg-reconfigure dash" does nothing, just opens new line. So i cannot change to bash
With ubuntu 22.04 i am able to complete all steps except last "./build_image.sh". Nothing happens, box selection window is not appearing.
Could you please help.

Thank you

**Comment by fairbird** [comment]
No need to change any thing with (sudo dpkg-reconfigure dash) Just ignore it ! and build image test on 23.04 and also 22.10 and no problem with building ...

Just follow the steps one by one carefully and then you must to add full log for error !
Do not for get to install (Dependencies)

**Comment by karikash11** [comment]
Hello.
after carefully followed all steps i was not able to build image on ubuntu 23.04 and 22.10. The same like on 23.10 and 22.04, dependencies install all ok without errors, cloning source all ok, but ./build_image.sh does not show "select boxes" menu. I don't even get error.
So i tried to build on linux mint and i was able to select box and image as build type, but now i have this problem:

Updating Git repositories...
Already up to date.
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-qt5.15'
Synchronizing submodule url for 'openembedded-core'
Cloning into '/home/jovo/openpli-dreambox-oe-core/bitbake'...
Cloning into '/home/jovo/openpli-dreambox-oe-core/meta-openembedded'...
Cloning into '/home/jovo/openpli-dreambox-oe-core/openembedded-core'...
Submodule path 'bitbake': checked out '40d00bf9308e0bf73a00134a99a012a292daa1c5'
Submodule path 'meta-openembedded': checked out 'd1b630342e8c1a81e0fda6ff5de2b8febd9634e5'
Submodule path 'meta-qt5.15': checked out 'c5f4bcaf1caf731e06470e26f561eec90d75cbd4'
Submodule path 'openembedded-core': checked out '163db4537b5844ff792e9dd462406c2d178939e0'
The openpli OE is now up-to-date.
Generating /home/jovo/openpli-dreambox-oe-core/build/env.source
Generating /home/jovo/openpli-dreambox-oe-core/build/conf/openpli.conf
Generating /home/jovo/openpli-dreambox-oe-core/build/conf/bblayers.conf
Generating /home/jovo/openpli-dreambox-oe-core/build/conf/local.conf
Building image for dm800sev2
check internet connection: Online      
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  python
make: *** [Makefile:109: image] Error 1
jovo@jovo-ThinkPad-T500:~/openpli-dreambox-oe-core$


Thank you

**Comment by fairbird** [comment]
1-Do not jump from distro to distro, just focus on the Ubuntu 23.10 nothing more ..
2-Do not use any thin from your side .. Just do what I wrote in the description and then post here the error ..

I have also update the description ...

**Comment by karikash11** [comment]
Hello,
Thank you for your help. Now i was able to build imag on ubuntu 23.10
But now i have problem with uploading feeds. Just to make sure, IP adress that goes in site.conf file should be my computer ip address? Is that correct?
This is error:

Updating Git repositories...
Already up to date.
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-qt5.15'
Synchronizing submodule url for 'openembedded-core'
The openpli OE is now up-to-date.
Building feed for dm800sev2
check internet connection: Online      
Loading cache: 100% |                                           | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:06:26
Parsing of 3594 .bb files complete (0 cached, 3594 parsed). 5487 targets, 753 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for runtime enigma2-plugin-extensions-audiosync (enigma2-plugins, enigma2-plugins-alliance)
Consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-audiosync
ERROR: Nothing RPROVIDES 'flash-scripts' (but /home/jovo/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupflash.bb RDEPENDS on or otherwise requires it)
recovery RPROVIDES flash-scripts but was skipped: incompatible with machine dm800sev2 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'flash-scripts' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['flash-scripts']
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'enigma2-plugin-extensions-backupflash', 'flash-scripts']

Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
jovo@jovo-ThinkPad-T500:~/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
You are trying to build image for dm800sev2 .. Look .. From my side no problem with building progress. working without any error ..

![Selection_001](https://github.com/fairbird/openpli-dreambox-oe-core/assets/1761779/b685ffa8-269e-4d59-86da-b987cb2ea2c0)

**Comment by karikash11** [comment]
Hi,
Building image was without problem finished.
My problem is building feed. Error i posted is from building feed.
Thank you

**Comment by fairbird** [comment]
Okay... Got it ..
Solved !
https://github.com/fairbird/openpli-dreambox-oe-core/commit/4ce28ebb3aa79a26554287bb9cb7e0341e284d2e

**Comment by karikash11** [comment]
Ok.
I will try later and let you know.
But just to make sure if i do it correct. In the last step before building feed is when i must put line DISTRO_HOST = " <your ip address or hostname> " in site.conf file. Do i put there my PC ip address or public ip address?
Thank you once again.

**Comment by fairbird** [comment]
https://github.com/fairbird/openpli-dreambox-oe-core/blob/develop/README.md?plain=1#L97

**Comment by fairbird** [comment]
@karikash11 
Please don't forget to close issue if everything done fine and solved your issues !

**Comment by karikash11** [comment]
Hi, now this ERROR :

ERROR: enigma2-plugin-skins-pd1loi-hd-night-2.6.1+git-r0 do_populate_lic: QA Issue: enigma2-plugin-skins-pd1loi-hd-night: The LIC_FILES_CHKSUM does not match for file://README.md;md5=212248d2a358bb604f3e8f7e3d14b4a1
enigma2-plugin-skins-pd1loi-hd-night: The new md5 checksum is bf787cb63f6ed5c8a1faf7273fe86695
enigma2-plugin-skins-pd1loi-hd-night: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
                            Pd1loi-HD-night Skin voor OpenPli 





^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
enigma2-plugin-skins-pd1loi-hd-night: Check if the license information has changed in /home/jovo/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/git/README.md to verify that the LICENSE value "GPL-3.0-only" remains valid [license-checksum]
ERROR: enigma2-plugin-skins-pd1loi-hd-night-2.6.1+git-r0 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/jovo/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/temp/log.do_populate_lic.506361
ERROR: Task (/home/jovo/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pd1loi-hd-night.bb:do_populate_lic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 12128 tasks of which 12093 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/jovo/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pd1loi-hd-night.bb:do_populate_lic
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by karikash11** [comment]
Everything is fine now.
Thanks for help, i really appreciate it.
