### ISSUE TITLE
ERROR: enigma2-alliance-plugins-git-r0 do_patch

### ISSUE THREAD

**Issue by elhawarynas** [fairbird/openpli-dreambox-oe-core#97]
ERROR: enigma2-alliance-plugins-git-r0 do_patch: Applying patch 'remove-unused-plugins.patch' on target directory '/home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm7080-oe-linux/enigma2-alliance-plugins/git/git'
CmdError('quilt --quiltrc /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm7080-oe-linux/enigma2-alliance-plugins/git/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch remove-unused-plugins.patch
patching file Makefile.am
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file Makefile.am
patching file configure.ac
Hunk #1 succeeded at 294 (offset 4 lines).
Hunk #3 succeeded at 383 (offset 4 lines).
Hunk #4 succeeded at 450 (offset 4 lines).
Patch remove-unused-plugins.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm7080-oe-linux/enigma2-alliance-plugins/git/temp/log.do_patch.253874
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-alliance-plugins.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 15210 tasks of which 14337 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-alliance-plugins.bb:do_patch
Summary: There was 1 ERROR message, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$

_Originally posted by @elhawarynas in https://github.com/fairbird/openpli-dreambox-oe-core/issues/73#issuecomment-2238166518_

**Comment by fairbird** [comment]
The source Under update in these days !

**Comment by elhawarynas** [comment]
Change CHKSUM to
DESCRIPTION = "PD1LOI HD night"
MAINTAINER = "pd1loi1"
LICENSE="GPL-3.0-only"
LIC_FILES_CHKSUM = "file://README.md;md5=7d3f230cd39b787fa1d165cd8ce229bf"
;md5=7d3f230cd39b787fa1d165cd8ce229bf
