### ISSUE TITLE
packagedata

### ISSUE THREAD

**Issue by elhawarynas** [fairbird/openpli-dreambox-oe-core#98]
ERROR: enigma2-alliance-plugins-git-r0 do_packagedata_setscene: Recipe enigma2-alliance-plugins is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime-reverse/enigma2-plugin-systemplugins-tempfancontrol
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime-reverse/enigma2-plugin-systemplugins-tempfancontrol-src
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/extended/enigma2-plugin-systemplugins-tempfancontrol.json.zstd
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/extended/enigma2-plugin-systemplugins-tempfancontrol-src.json.zstd
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol-src
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol-src.packaged
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol.packaged
    (matched in manifest-dm800se-enigma2.packagedata)
Please adjust the recipes so only one recipe provides a given file. 
WARNING: Logfile for failed setscene task is /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm800se-oe-linux/enigma2-alliance-plugins/git/temp/log.do_packagedata_setscene.3744630
WARNING: Setscene task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-alliance-plugins.bb:do_packagedata_setscene) failed with exit code '1' - real task will be run instead
WARNING: ubuntu-font-family-0.80-r0 do_fetch: Failed to fetch URL http://font.ubuntu.com/download/ubuntu-font-family-0.80.zip, attempting MIRRORS if available
WARNING: zeroconf-0.9-r0 do_fetch: Failed to fetch URL http://www.progsoc.org/~wildfire/zeroconf/download/zeroconf-0.9.tar.gz, attempting MIRRORS if available
ERROR: enigma2-alliance-plugins-git-r0 do_packagedata: Recipe enigma2-alliance-plugins is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime-reverse/enigma2-plugin-systemplugins-tempfancontrol
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime-reverse/enigma2-plugin-systemplugins-tempfancontrol-src
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/extended/enigma2-plugin-systemplugins-tempfancontrol.json.zstd
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/extended/enigma2-plugin-systemplugins-tempfancontrol-src.json.zstd
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol-src
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol-src.packaged
    (matched in manifest-dm800se-enigma2.packagedata)
  /home/elhawary/openpli-dreambox-oe-core/build/tmp/pkgdata/dm800se/runtime/enigma2-plugin-systemplugins-tempfancontrol.packaged
    (matched in manifest-dm800se-enigma2.packagedata)
Please adjust the recipes so only one recipe provides a given file. 
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm800se-oe-linux/enigma2-alliance-plugins/git/temp/log.do_packagedata.4090998
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-alliance-plugins.bb:do_packagedata) failed with exit code '1'
NOTE: Tasks Summary: Attempted 14506 tasks of which 12981 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-alliance-plugins.bb:do_packagedata
    log: /home/elhawary/openpli-dreambox-oe-core/build/tmp/work/dm800se-oe-linux/enigma2-alliance-plugins/git/temp/log.do_packagedata.4090998
Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:113: feed] Error 1

**Comment by elhawarynas** [comment]
I think there is a duplicate of this file 
enigma2-alliance-plugins\
I deleted it and the build completed without problems
Is one of the files a duplicate of the other?

	enigma2-plugins-alliance\
	enigma2-alliance-plugins\
The two files are located in 
openpli-enigma2-feed.bb

**Comment by fairbird** [comment]
There are tow diffrent file 
They are two different files because of the plugins they contain, and neither of them can be removed from the feed build.
Each file has its own source.
github.com/oe-alliance/enigma2-plugins.git
github.com/oe-alliance/oe-alliance-plugins.git

And I did not got any error with built feed ... And I will try also to build feed for dm800se to make more sure.

**Comment by fairbird** [comment]
Solved !
https://github.com/fairbird/openpli-dreambox-oe-core/commit/efe18c8e7e04d9ba0bb3c8fb54baebc88dba5eef
