### ISSUE TITLE
ERROR:

### ISSUE THREAD

**Issue by elhawarynas** [fairbird/openpli-dreambox-oe-core#99]
ERROR: enigma2-plugin-systemplugins-autobouquetsmaker-3.3+git-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus,guid=a8cccc16ed2e385a3549185d67516bb3"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot-native/usr/bin/python3-native:/home/elhawary/openpli-dreambox-oe-core2/openembedded-core/scripts:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot/usr/bin/crossscripts:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot-native/usr/sbin:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot-native/usr/bin:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot-native/sbin:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/recipe-sysroot-native/bin:/home/elhawary/openpli-dreambox-oe-core2/bitbake/bin:/home/elhawary/openpli-dreambox-oe-core2/build/tmp/hosttools"; export HOME="/home/elhawary"; LANG=C git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all -c clone.defaultRemoteName=origin fetch -f --progress https://github.com/oe-alliance/AutoBouquetsMaker.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* failed with exit code 128, see logfile for output
ERROR: enigma2-plugin-systemplugins-autobouquetsmaker-3.3+git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/oe-alliance/AutoBouquetsMaker.git;protocol=https;branch=master')
ERROR: Logfile of failure stored in: /home/elhawary/openpli-dreambox-oe-core2/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-systemplugins-autobouquetsmaker/3.3+git/temp/log.do_fetch.179259
ERROR: Task (/home/elhawary/openpli-dreambox-oe-core2/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-autobouquetsmaker.bb:do_fetch) failed with exit code '1'

**Comment by fairbird** [comment]
You should know the issue. It is not first time happens to you brother !
> ERROR: enigma2-plugin-systemplugins-autobouquetsmaker-3.3+git-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export

The problem is fetch from autobouquetsmaker plugin source. not from core. It is just from your side. With me no problem at all . The source online (works)
[github.com/oe-alliance/AutoBouquetsMaker.git](https://github.com/oe-alliance/AutoBouquetsMaker)
